### ISSUE TITLE
header file listed twice on readme

### ISSUE THREAD

**Issue by hazendaz** [megastep/makeself#102]
Another one - header file is listed twice.  The first one I assumed was to have file afterwards.  The second one confirms that assumption.

As I get a little deeper into building a maven plugin around this I'll start looking in the source.  At the moment, I have the baseline working and I'm just in the process of building out support for all elements.

**Comment by realtime-neil** [comment]
@megastep propose closing this because it's old and I can't find the referenced bug anywhere in the history of the `README.md` file.
