### ISSUE TITLE
Maven Plugin for makeself

### ISSUE THREAD

**Issue by hazendaz** [megastep/makeself#103]
Hi, I have pushed an initial rough cut of maven plugin for this project.  The basic baseline required fields has been tested to be working.

[makeself-maven-plugin](https://github.com/hazendaz/makeself-maven-plugin)

I have also released this to sonatype under snapshots

[sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/github/hazendaz/maven/makeself-maven-plugin/1.0.0-SNAPSHOT/)

Enjoy!

**Comment by megastep** [comment]
Thanks but no need to create an issue for this!

**Comment by hazendaz** [comment]
True but wasn't sure of another way to provide you that information in case you are interested or anyone out there using your solution.
