### ISSUE TITLE
New solaris incompatibility with --untar-extra option

### ISSUE THREAD

**Issue by rbcrwd** [megastep/makeself#106]
Commit d7b5a6a34ebc2e5b8364a815ad734974afe4ffb9 (specifically, the changes to makeself-header.sh) introduces an issue with Solaris compatibility:

```
diff --git a/makeself-header.sh b/makeself-header.sh
index 35ec817..2d6f287 100755
--- a/makeself-header.sh
+++ b/makeself-header.sh
@@ -214,10 +214,10 @@ MS_Check()
 UnTAR()
 {
     if test x"\$quiet" = xn; then
-               tar \$1vf - 2>&1 || { echo Extraction failed. > /dev/tty; kill -15 \$$; }
+               tar \$1 "$UNTAR_EXTRA" -vf - 2>&1 || { echo Extraction failed. > /dev/tty; kill -15 \$$; }
     else

-               tar \$1f - 2>&1 || { echo Extraction failed. > /dev/tty; kill -15 \$$; }
+               tar \$1 "$UNTAR_EXTRA" -f - 2>&1 || { echo Extraction failed. > /dev/tty; kill -15 \$$; }
     fi
 }
```

I have yet to debug precisely how that's broken on Solaris and not Linux targets, but the result is that the extracted data is corrupted - the MD5 doesn't match, and when that's "fixed", gzip comes back complaining that the data is "encrypted".

Hand-reverting that patch fixes the issue for me.  My guess is that Solaris tar isn't taking the empty arg kindly.  It also warrants pointing out that if UNTAR_EXTRA is quoted like that, it could (in some cases) get passed as a single arg.  Great if you're doing a single, solid arg (e.g., "--exclude=.git"), but if you add multiple args, the shell may pass them as one and confuse tar (e.g., "tar '-x -v -f'" rather than "tar -x -v -f").

**Comment by megastep** [comment]
Thanks for this! I merged your pull request.
