### ISSUE TITLE
How to add a custom command option

### ISSUE THREAD

**Issue by dk1301** [megastep/makeself#112]
Hi all,
I'm wondering whether there is a way add a custom command option that can afterwards be manipulated by the startup script.
e.x
makeself.sh --bzip2 myprogram/ myprogram.bz2.run  ./startup_script.sh --custom option
so that the "--custom option" to be manipulated by the startup_script.

 Thanks in advance

**Comment by megastep** [comment]
If you're asking whether the embedded script can be passed arguments, that is already possible.

**Comment by dk1301** [comment]
Is there an example to cross check it ?
