### ISSUE TITLE
Command-line argument to continue without prompt?

### ISSUE THREAD

**Issue by ashes999** [megastep/makeself#113]
Context: I'm trying to build MonoGame on Linux as part of Travis-CI. To do this, I need to install MonoGame (via `./monogame-sdk.run`). (Travis-CI spins up a Docker container per build, so the build has to bootstrap itself.)

Currently, after the initial set of checks for pre-requisites, the install script prompts me to confirm/continue that I want to install. The exact prompt is: `Continue (Y, n):`

I've tried to pipe output to the process somehow, without success. As far as I can tell, there's no command-line argument to simply install (without prompting for confirmation).  I even checked the generated script code, but didn't see anything.

Is there any way to install this without user intervention?

If not, can you please consider this a feature request, and suggest how I can get around this?

As far as I can tell, MonoGame used Makeself for at least three releases, and an older version (from two releases ago) didn't require user input to install.

**Comment by mikedld** [comment]
It's not makeself displaying this message but the script embedded into the package that is put there by package creators. You could do

```console
% ./monogame-sdk.run --noexec --keep --target /tmp/monogame
```

to extract the package contents and you'll see the postinstall.sh script there containing

```sh
read -p "Continue (Y, n): " choice2
case "$choice2" in
        n|N ) exit ;;
        *) ;;
esac
```

Since this is the script that is being started by makeself after extraction, you could e.g. do the extraction youself, then patch the script however you want and run it manually.

**Comment by megastep** [comment]
@mikedld is correct. This is not actually a Makeself bug.

**Comment by ashes999** [comment]
Sorry, I wasn't clear on whether the prompt was from Makescript or MonoGame. (I asked on the MonoGame forums about this and didn't get any response.)

I'll try your suggestion @mikedld . Thanks for providing details.

**Comment by ashes999** [comment]
Verified: when I extract the package and run `postinstall.sh`, the underlying script still asks me for confirmation. This is definitely coming from MonoGame. I'll move this discussion over to their repo.

Thanks!
