### ISSUE TITLE
2.3.1 does not self extract

### ISSUE THREAD

**Issue by hazendaz** [megastep/makeself#114]
Not sure what the issue but 2.3.1 doesn't work on extraction.  Look at 2.3.0 in comparison.  Version 2.3.1 shows an argument --notemp.  I assume there is some problem here.

~/Java/_build/makeself
$ ./makeself-2.3.1.run
Verifying archive integrity...  100%   All good.
Uncompressing Makeself v2.3.1  100%
Makeself has extracted itself. --notemp

~/Java/_build/makeself
$ ./makeself-2.3.0.run
Creating directory makeself-2.3.0
Verifying archive integrity...  100%   All good.
Uncompressing Makeself v2.3.0  100%
Makeself has extracted itself

**Comment by megastep** [comment]
What OS are you running this on?

**Comment by hazendaz** [comment]
git bash in windows

**Comment by bashlakov** [comment]
Same behaviour, Mac OS 10.12.6

abashlakov:temp a.bashlakov$ ./makeself-2.3.0.run 
Creating directory makeself-2.3.0
Verifying archive integrity...  100%   All good.
Uncompressing Makeself v2.3.0  100%  
Makeself has extracted itself
abashlakov:temp a.bashlakov$ ./makeself-2.3.1.run 
Verifying archive integrity...  100%   All good.
Uncompressing Makeself v2.3.1  100%  
Makeself has extracted itself. --notemp
abashlakov:temp a.bashlakov$

**Comment by megastep** [comment]
Oops, I think it might actually be my fault, used the wrong order of flags when creating the archive. I'll fix it and re upload.

**Comment by megastep** [comment]
My bad, download the archive again and it should be fine.

**Comment by hazendaz** [comment]
Thanks!  This works now.

**Comment by bashlakov** [comment]
Thanks for fix, it work now!
