### ISSUE TITLE
extract without execution

### ISSUE THREAD

**Issue by treaki** [megastep/makeself#115]
hi,

i dont want to execute foreign code on my machine just to extract files. How can i extract all the data without executing any code included? i have an archive here where i was able to strip all ASCII before the gzip data using a hex editor and then run gzip and tar over it to get some files. But unfortunately there where more then one binary blobs included in the "makeself binary"... So how can i get all the files?

```
$ stat -c "%n filesize: %s" *
gog_master_of_magic_2.0.0.3.sh filesize: 17758688
gog_master_of_magic_2.0.0.3.sh_ filesize: 17746226
log filesize: 418
$ cat log
$ gzip -v -t -l gog_master_of_magic_2.0.0.3.sh_
method  crc     date  time           compressed        uncompressed  ratio uncompressed_name
defla 1c1a0000 Aug 16 21:16            17746226                 259 -6851717.8% gog_master_of_magic_2.0.0.3.sh_
$ gzip -v -t gog_master_of_magic_2.0.0.3.sh_
gog_master_of_magic_2.0.0.3.sh_:	
gzip: gog_master_of_magic_2.0.0.3.sh_: decompression OK, trailing garbage ignored
 OK
$ 

```
gog_master_of_magic_2.0.0.3.sh is the original file i have got, gog_master_of_magic_2.0.0.3.sh_ the result of deleting everything until the binary (non textual/ASCII-like) data started, but it looks like there is more then one blob. As you can see gzip claims that there are more data trailing the gzip archive, and when i extract it i miss the important stuff (just a launcher i dont need anyway)...

So i would need a tool that would show me any blobs position inside an makeself archive like this imaginary tool:

```
$ makeselfarchiveanalzyer gog_master_of_magic_2.0.0.3.sh
opening gog_master_of_magic_2.0.0.3.sh for analyzing, overall file size 17758688; showing containing blobs:
start; end; type
12462; xxx; tar.gz archive
yyy; zzz; whatever there is
[...]
```
i am incapable of understanding the magic behind this binary blob stuff in use with makeself so i would be really glad if someone could help me out. Thanks in advance!

**Comment by midicase** [comment]
--noexec is the option you want.

**Comment by JessePelton** [comment]
You'll want to use --keep as well (--noexec --keep) so the extracted files won't be removed immediately after being extracted:
`gog_master_of_magic_2.0.0.3.sh --noexec --keep`

**Comment by realtime-neil** [comment]
Propose closing this because the initial question has been asked and answered.
