### ISSUE TITLE
gpg-encrypt error: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by pavlodvornikov** [megastep/makeself#116]
Hello,

I have setup with clean Ubuntu 17.04 server and makeself release version 2.3.1. Following error appears when I am trying to make gpg encrypted archive:
```
$ makeself/makeself.sh --gpg-encrypt test test.run "test" ./test.sh
Header is 554 lines long

About to compress 8 KB of data...
Adding files to archive named "test.run"...
./
./test.sh
gpg: directory '/home/user/.gnupg' created
gpg: new configuration file '/home/user/.gnupg/dirmngr.conf' created
gpg: new configuration file '/home/user/.gnupg/gpg.conf' created
gpg: keybox '/home/user/.gnupg/pubring.kbx' created
gpg: problem with the agent: Inappropriate ioctl for device
gpg: error creating passphrase: Operation cancelled
gpg: symmetric encryption of '[stdin]' failed: Operation cancelled
Aborting: archive directory not found or temporary file: /tmp/mkself1460 could not be created.
```

gpg version:
```
$ gpg -h
gpg (GnuPG) 2.1.15
libgcrypt 1.7.6-beta
```

Please let me know if you need any additional details/debug info.

**Comment by megastep** [comment]
This looks like something to do with your GPG setup, maybe you hadn't set up your keys and environment before you got started?

**Comment by pavlodvornikov** [comment]
@megastep, you are right, keys and environment have not been set up before start. Log says that they was created automatically. I think the problem is in changes in gpg2 version. According to Arch's GpuPG [doc](https://wiki.archlinux.org/index.php/GnuPG#Unattended_passphrase), option ```--pinentry-mode loopback``` could be used to resolve issue and it works:
```
$ makeself/makeself.sh --gpg-encrypt --gpg-extra "--pinentry-mode loopback"  test test.run "test" ./test.sh
Header is 556 lines long

About to compress 8 KB of data...
Adding files to archive named "test.run"...
./
./test.sh
gpg: directory '/home/wispear/.gnupg' created
gpg: new configuration file '/home/wispear/.gnupg/dirmngr.conf' created
gpg: new configuration file '/home/wispear/.gnupg/gpg.conf' created
gpg: keybox '/home/wispear/.gnupg/pubring.kbx' created
CRC: 1925553927   
MD5: 05be26b3ce30593e0cc44c587c82d115

Self-extractable archive "test.run" successfully created.
```

Should this gpg version check be on user side or on software side ?

**Comment by megastep** [comment]
I think the general assumption as far as Makeself is concerned is that the users should have a proper GPG setup when invoking these options.

**Comment by pavlodvornikov** [comment]
OK, then this issue could be closed.
