### ISSUE TITLE
makeself not finding startup_script on Ubuntu 17.10

### ISSUE THREAD

**Issue by logileifs** [megastep/makeself#122]
I'm trying to make a startup script as shown in the documentation
`$ makeself.sh /home/logi/mysoft mysoft.sh "Logi's nice software package" ./setup`

The setup script is there before I create the package and executable by anyone
`$ ls -ls mysoft`
`4 -rwxrwxr-x 1 logi logi 47 nóv 13 10:29 setup`

I have also verified that it's in the package after creation

`$ ./mysoft.sh --list`

```
Target directory: mysoft
drwxrwxr-x logi/logi         0 2017-11-13 10:29 ./
-rwxrwxr-x logi/logi        47 2017-11-13 10:29 ./setup
```

But when I run the package, the script isn't found
`$ ./mysoft.sh`

```
Verifying archive integrity...  100%   All good.
Uncompressing Logi's nice software package  100%  
./mysoft.sh: 1: eval: ./setup: not found
```

Although this works:
`$ makeself.sh /home/logi/mysoft mysoft.sh "Logi's nice software package" echo "this is the setup script"`

`$ ./mysoft.sh`

```
Verifying archive integrity...  100%   All good.
Uncompressing Logi's nice software package  100%  
this is the setup script
```

Am I missing something here or is this a bug?

**Comment by megastep** [comment]
Instead of just `./setup` as the argument for makeself, you could try to replace it with `sh setup` instead (or whichever shell is needed by your script).

**Comment by logileifs** [comment]
hey thanks, that works! I assumed the dot was needed because the path might not be the same, but why not say `sh setup` in the documentation instead then since `./setup` doesn't work ?

**Comment by mikedld** [comment]
It could be that the shebang line in the script is incorrect. For instance, I'm usually seeing this error when the script contains Windows (CR+LF) line endings instead of UNIX (LF) ones (e.g. a developer copied the script from a Windows machine to a *NIX one), and so CR becomes a part of interpreter path/name, i.e. `#!/bin/sh<CR>` or `#!/usr/bin/env bash<CR>`. Something worth checking.

**Comment by logileifs** [comment]
@mikedld in my case I was writing and running on the same Ubuntu system so I don't think any windows line endings managed to sneak in there. I did however use `#!/usr/bin/sh` when I maybe should have used `#!/usr/bin/env bash` or something else

**Comment by megastep** [comment]
Yeah just to work around these kinds of issues, it's probably safer to invoke the script via its shell. Using `./setup` would be more appropriate if you are bundling a compiled binary for instance.
