### ISSUE TITLE
Target option cannot handle spaces

### ISSUE THREAD

**Issue by mtdew365** [megastep/makeself#130]
I am using the following command....

makeself.sh --xz --complevel 9e --target "Master of Magic" "Master of Magic" MOM_140n.xz.run "Master of Magic v1.40n"

It creates directories Master, of, Magic all in the current directory.

If I use --target "Master_of_Magic" it works as expected .... creates a directory Master_of_Magic and puts all the files under that.

I have tried \, ", and ' all with the same result.  I am running version 2.3.0 on fedora 27.

How do I use the --target option to create a directory with spaces?

**Comment by mikedld** [comment]
FYI I believe I saw similar/same results with FreeBSD's getopt, while installing and using the GNU one worked just fine.

**Comment by megastep** [comment]
Looks like the code handling the parameter to `--target` was not escaping the string properly. I'm committing a fix for this.
