### ISSUE TITLE
Issue when target directory has spaces

### ISSUE THREAD

**Issue by mtdew365** [megastep/makeself#131]
#130 was closed but I am still receiving an error when using spaces....  I just downloaded the newest version....

/home/jbergmann/makeself/makeself.sh --xz --complevel 9e --header "/home/jbergmann/makeself/makeself-header.sh" --target "Master of Magic" "Master of Magic" MOM_140n.xz.run "Master of Magic v1.40n"
/home/jbergmann/makeself/makeself.sh: line 432: test: too many arguments
Header is 571 lines long

About to compress 39120 KB of data...
Adding files to archive named "MOM_140n.xz.run"...

When I run it I will still get all three directories (Master, of, Magic) added instead of the archive creating one directory called 'Master of Magic' and placing all files under that. Am I missing a step?

**Comment by mtdew365** [comment]
Yes.  I used the following...

git clone https://github.com/megastep/makeself.git $HOME/makeself
git pull

to get the latest version.

**Comment by megastep** [comment]
Ok, try again, it looks like I needed to do the same thing to the call to `mkdir`. I think it should work now.

**Comment by mtdew365** [comment]
Well.... it kind of works...

[jbergmann@jason-laptop-hp GOG Games]$ /home/jbergmann/makeself/makeself.sh --xz --complevel 9e --header "/home/jbergmann/makeself/makeself-header.sh" --target "Master of Magic" "Master of Magic" MOM_140n.xz.run "Master of Magic v1.40n"
/home/jbergmann/makeself/makeself.sh: line 432: test: too many arguments
Header is 571 lines long

About to compress 39120 KB of data...
Adding files to archive named "MOM_140n.xz.run"...

But it completes as... 
Self-extractable archive "MOM_140n.xz.run" successfully created.

When I run it....
[jbergmann@jason-laptop-hp z]$ ./MOM_140n.xz.run 
Creating directory Master of Magic
Verifying archive integrity...  100%   All good.
Uncompressing Master of Magic v1.40ndf: Master: No such file or directory
  100%  
[jbergmann@jason-laptop-hp z]$ ls -al
total 14292
drwx--x--x. 3 jbergmann jbergmann     4096 Apr 15 20:47  .
drwxrwxr-x. 3 jbergmann jbergmann     4096 Apr 15 11:14  ..
drwx--x--x. 7 jbergmann jbergmann     4096 Apr 13 20:44 'Master of Magic'
-rwxrwxr-x. 1 jbergmann jbergmann 14622509 Apr 15 20:47  MOM_140n.xz.run

It appears to be correct but it gives an error, listed above.

**Comment by megastep** [comment]
Mmh, ok I guess there's still a few other places where we need to handle this case better. Hold on...

**Comment by megastep** [comment]
See if what I just committed helps.

**Comment by mtdew365** [comment]
Appears to work correctly....

 /home/jbergmann/makeself/makeself.sh --xz --complevel 9e --header "/home/jbergmann/makeself/makeself-header.sh" --target "Master of Magic" "Master of Magic" MOM_140n.xz.run "Master of Magic v1.40n"
Header is 571 lines long

About to compress 39120 KB of data...
Adding files to archive named "MOM_140n.xz.run"...

Ended with .... Self-extractable archive "MOM_140n.xz.run" successfully created.

Extracting...
./MOM_140n.xz.run 
Creating directory Master of Magic
Verifying archive integrity...  100%   All good.
Uncompressing Master of Magic v1.40n  100%  
[jbergmann@jason-laptop-hp z]$ ls -al
total 14296
drwx--x--x. 3 jbergmann jbergmann     4096 Apr 15 21:37  .
drwxrwxr-x. 3 jbergmann jbergmann     4096 Apr 15 11:14  ..
drwx------. 7 jbergmann jbergmann     4096 Apr 13 20:44 'Master of Magic'
-rwxrwxr-x. 1 jbergmann jbergmann 14624435 Apr 15 21:37  MOM_140n.xz.run

After extracting, the program runs correctly.  Thanks for all the help.  This appears to fix the issue.
