### ISSUE TITLE
Make run output match that of --check

### ISSUE THREAD

**Issue by hazendaz** [megastep/makeself#136]
final file with --check option is more clear than the actual run.  Please add the same output text so it's clear what the percentages mean.

Example.

```
$ ./installGit.sh --check
Verifying archive integrity...  100%   SHA256 checksums are OK.  100%   MD5 checksums are OK. All good.

$ ./installGit.sh
Verifying archive integrity...  100%    100%   All good.
Uncompressing Git Self Extraction  100%
I'm pretending to do something great!
```

--check shows SHA256 checksums are OK. and MD5 checksums are OK.  This is helpful as too many questions are asked about what those percentages mean and --check is pretty clear.

**Comment by megastep** [comment]
Good point, I actually am not sure why it is this way right now!

**Comment by megastep** [comment]
Should be fixed now.

**Comment by hazendaz** [comment]
Great!  Thanks so much!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
