### ISSUE TITLE
GUI while uncompressing

### ISSUE THREAD

**Issue by dguayrobotiq** [megastep/makeself#141]
Is there a way to have a custom GUI while `makeself` package is uncompressing? I already run `makeself` with `--nox11`.

**Comment by megastep** [comment]
Not really. The `--nox11` option is to prevent Makeself from spanning a new xterm or similar to run the script. To have a custom GUI before the archive is uncompressed, we'd need a way to inform a third-party program of the progress of the decompression and we just don't have a way to do that at the moment.

**Comment by dguayrobotiq** [comment]
@megastep Ok thanks !
