### ISSUE TITLE
--sha256 does not support the --append feature

### ISSUE THREAD

**Issue by shloim** [megastep/makeself#143]
I've reverted the problematic commit [3cac577](https://github.com/megastep/makeself/commit/3cac577c74517bd7d646abe1e8d3c3899882cc8b) mentioned in issue #48 

CRCsum and MD5 support the appending of additional checksums while appending
SHA replaces the checksum with the last calculated checksum instead of appending it to the SHA array:

CRCsum="4114216492 924515856"
MD5="1ba1b13d90281c1b9c487c36d1cdeb68 92cb2b53fd052bbaa9bedfdc43787948"
**SHA=" ce38c5353a5ef8a5f85fbf84c3e810394730fbfaf2d4e2268b46397506ab9573"**
filesizes="72690465 2748141"

**Comment by megastep** [comment]
That sounds like a real problem. Should be easy to fix.

**Comment by megastep** [comment]
This should now be fixed.
