### ISSUE TITLE
Support for logging?

### ISSUE THREAD

**Issue by openface** [megastep/makeself#144]
I’d like for the installer output to be captured to a log file (in addition to STDOUT).  Is there any way or plans to support this?

**Comment by megastep** [comment]
Not really builtin, though I would imagine you could do this as part of your installation script, unless you want to capture output from Makeself itself as well.

**Comment by openface** [comment]
Ideally, output from the installation script could be redirected to a log file - to capture output/errors.  Adding this to the installation script will suffice however.  Thanks!
