### ISSUE TITLE
None of generated archives are able to execute start script

### ISSUE THREAD

**Issue by aquacode** [megastep/makeself#146]
Seems no matter what I do my start scripts don't execute when running the generated archive.
I've made certain the original script is executable.
I've tried setting the startup script to be ./startup.sh and "sh startup.sh" and neither approach works. I've also tried "sudo startup.sh" (since I'm running as root).

I either get "Permission denied" or "No such file or directory" or "Command not found"

I have even extracted the contents of the archive and then manually ran the startup script and it runs successfully if extracted first.

Here is sample of directory being used to create archive:
/appinstall
- abc.war
- def.war
- startup.sh

Then I run:
./makeself.sh appinstall appinstall.run "Generic message" ./startup.sh

Not sure what I am doing wrong. Any assistance is appreciated.

**Comment by megastep** [comment]
Personally I usually specify `sh startup.sh` for these kinds of archives. This makes sure that the execute permissions on the scripts are not important. You might want to try to extract the archive manually with `--target` and `--noexec` to troubleshoot this further.

**Comment by aquacode** [comment]
So, I had in fact tried `sh startup.sh` but more specifically, `"sh startup.sh"` and the quotes didn't work, which I'm sure you will nod your head to.
I ended up going with: `bash startup.sh` and I'm beyond that trouble.
The script itself actually called another executable in the archive, a Go executable actually, but that didn't work. Instead, I seemed to have to `cp` the Go executable "outside" to filesystem in order to run it. Any ideas?

**Comment by katakombi** [comment]
I'm having similar issues when trying to execute my installers from a graphical file browser. When I "run in terminal" they work as expected and when I just run them they do nothing. I wonder what am I doing wrong ... I've checked a GOG game and they use makeself v 2.2 and they work in both cases, but when I download makeself.run even that won't work! 
I am using Linux Mint Mate.
