### ISSUE TITLE
can makeself support android ? If not, do you have plan to support?

### ISSUE THREAD

**Issue by raymond1860** [megastep/makeself#147]
I want to use it on android native binary. Is it possible?

**Comment by megastep** [comment]
I'm not sure what your use case is here - if it's to distribute an Android application as a package to be open somewhere else, then sure. If it's to extract an archive on an Android device, I'm not sure that's possible (there might not even be a usable shell available, let alone its supporting commands).

**Comment by raymond1860** [comment]
Thanks for your very fast feedback.
No , I am not to distribute APK file using makeself. I just want to packing native program (well ,you know low level of android is linux) but using bionic c library.
What I concern is lacking of some dependencies for makeself packing and extracting on android platform.

**Comment by megastep** [comment]
I doubt this is very feasible because besides Android using a Linux kernel it will still very likely many of the Unix shell tools we rely on...
