### ISSUE TITLE
suid problems

### ISSUE THREAD

**Issue by mirkovich0** [megastep/makeself#152]
Well... I've created a self extractable file that installs a file in `/usr/bin`. It completly messed up my Linux installation.

Let's suppose you create `myprogram` into `myfolder`. Then you create `myinstaller.sh` with the following command:
`makeself --target /usr/bin myfolder myinstaller.sh "Installer for myprogram"`

Then, you'll need to sudo to install it (it will just fail if you're not sudoing).
`sudo ./myinstaller.sh`

It will successfully install myprogram to `/usr/bin`... but while doing so will reset file ownership and suid (and group suid) flags **for existing files on the folder**. Note that this includes `/usr/bin/sudo`.
Not a cool thing.

(As a workaround: I can do `rm $0 ; mv * /usr/bin` inside an install script and it works just fine).

Regards.

**Comment by megastep** [comment]
Frankly Makeself was never designed nor intended to be used to install system software in this matter; using `--target /usr/bin` is an extraordinarily dangerous thing to trust to a third-party script.

The proper way to do this is rather to have your own installer program run from a temporary directory that Makeself creates for you, and make sure files are copied properly.

**Comment by mirkovich0** [comment]
I can't tell what the original purpose of the program was (and whether this should change or not) and why would you limit it to "not system folder" operations, even when the program doesn't warn you. I can tell you, that I like the way it works (most of the time) and that it's very useful for example, to create a simple automated installer from within a makefile for the Jenkins I have running.

It seems a rather simple operation: extract some files to a folder (system or not); I think **it shouldn't mess up the permissions nor owners of the files already there** (therefore, I still think this is a buggy behaviour). Worst case scenario: you're extracting to some system folder (like I did), but even on a regular folder this is software misbehaving. I think it is a valid use of the program and the fact that it breaks things is an issue.

**Comment by mirkovich0** [comment]
I don't want to be rude, but I think you're just denying a real problem. If it's not the expected behaviour, it's a bug.
a) Don't make it about the use. This issue is not about the use, it's about the program changing permissions and ownership of files it shouldn't touch which are in the same folder. **This is not the expected behaviour, this is a bug**.
b) It's meant to be run as root. That's why you have a **--needroot** option!!!
c) I'm trusting makeself the moment 1) it's open source. 2) I've seen a bit of what the install script does (altough I haven't found yet why it destroys ownership/permissions) 3) it's packed with Ubuntu to be downloaded via apt-get, so I trust there's a community reviewing.
d) If you don't trust a piece of software, **you shouldn't install it on the first place at all**. You have permissions to write **.bashrc**, so any software as a regular user can do something along the lines of `alias sudo='sudo rm -rf ;'` or `PATH=/path/to/fake/sudo:$PATH` and you will be destroying your machine the next time you do `sudo apt` just the same; no need to be run as root.
e) Doesn't make any sense to me, having an option to extract to a certain folder, to put an installer if all I want is to extract a file to a folder. Like I said, _this bug can be worked around putting an installer_, I'm aware of that, but still a bug. I do put an installer when there are prerequisites (checking certain libraries for example), but here it doesn't make any sense: I just want to copy one file to a folder. Anyway, if you're forcing me to put an installer just to copy one file to an existing folder... Why do we have a **--target** option?

Regards.

**Comment by realtime-neil** [comment]
@mirkovich0 why didn't you use the `--nochown` option? I also agree with @megastep ; naming `/usr/bin`, while technically valid, seems overly aggressive for the sake of expediency.

**Comment by mirkovich0** [comment]
> @mirkovich0 why didn't you use the `--nochown` option? I also agree with @megastep ; naming `/usr/bin`, while technically valid, seems overly aggressive for the sake of expediency.

a) The origin to the post is to report a problem, not to seek workarounds. Like I said, I can work around it with a custom installer script.
b) The point is to make an autoextracting file that can be run without command line parameters; that's why I specify `--target` when I create the autoextracting and not on extraction. Imagine you download a .run from a webpage you trust and you forget `--nochown` and that results in an unusable computer.
c) It shouldn't chown if it's not necessary (why would it mess with files and folders that were already there, and that I'm not creating? `/usr/bin` exists, no need to mess with it; `/usr/bin/sudo` exists and it's not the file I'm extracting, why chown it?... and why would you chown to root a file that's already owned by root)
d) `--nochown` should be the default; `--chown` should be added and used when needed (if ever needed, I don't see the point of chowning anything). It's more benign to deny extraction if you missed a `--chown` parameter (your fault after all), than destroy permissions and ownership if you missed a `--nochown` (not your fault).

**Comment by realtime-neil** [comment]
@mirkovich0 point taken. Do I assume correctly that you would modify the `chown` invocation to something more selective?

**Comment by mirkovich0** [comment]
@realtime-neil It's a good idea. When I have some time, I will try to see in depth what's the actual problem and try to make a patch.

**Comment by realtime-neil** [comment]
Propose closing this since it was fixed in #157 .
