### ISSUE TITLE
Fail Ram

### ISSUE THREAD

**Issue by liberodark** [megastep/makeself#160]
Hi,

 Have crash for make a big sfx with 7Go have 8 Ram.
My tmp is 3.9 Go.

Have try to make : 
`./makeself.sh --notemp --nocomp --nox11 Folder/ sfx.sh archive.fa ./my.sh`

But is not work

tar: Error is not recoverable: exiting now
ERROR: failed to create temporary archive: /tmp/mkself2924.tar

Other option have try : 

`./makeself.sh --nox11 Folder/ sfx.sh archive.fa ./my.sh`
But this take all ram and crash...

You have idea ?

**Comment by megastep** [comment]
Try to set the `TMPDIR` environment variable to a location with enough disk space available, i.e. `export TMPDIR=/home/directory/tmp` before running the command.

**Comment by liberodark** [comment]
ok have fixe script :D 
And change tmpdir to home
