### ISSUE TITLE
md5 verification fails under busybox

### ISSUE THREAD

**Issue by Kevin0626** [megastep/makeself#161]
I created the self installation package under ubuntu16.04 and run it under busybox on target.

it fails in the md5 check. it looks the "head" command used a option 's' that is not supported busybox. 

root@am335x:~# . ./ams_client-arm-a7-2019-5-4.sh
Verifying archive integrity...head: invalid option -- 's'
BusyBox v1.20.2 (2013-06-25 16:43:45 CDT) multi-call binary.

Usage: head [OPTIONS] [FILE]...

-sh: -sh: No such file or directory
Error in MD5 checksums: d41d8cd98f00b204e9800998ecf8427e is different from cd520c118a3d9e260648ae3280fccfdf

**Comment by megastep** [comment]
This is rather odd, as I'm not aware of `-s` being used anywhere when calling `head`. It should always be calls in the form of `head -n`

**Comment by droberg** [comment]
I have this issue too, no warnings about head though. Only the failing md5sum

**Comment by droberg** [comment]
"dd" under busybox does not have these options 
- ibs
- obs 
- convert

**Comment by droberg** [comment]
As a workaround I changed the "--noprogress" part in makeself-header.sh to not use ibs and obs, so that it now kindof work: 

-    dd if="\$1" ibs=\$2 skip=1 obs=1024 conv=sync 2> /dev/null | \\
-    { test \$blocks -gt 0 && dd ibs=1024 obs=1024 count=\$blocks ; \\
-      test \$bytes  -gt 0 && dd ibs=1 obs=1024 count=\$bytes ; } 2> /dev/null
+    dd if="\$1" bs=\$2 skip=1

**Comment by realtime-neil** [comment]
@droberg I don't think it's fair to say "Busybox" when what you mean is "Busybox configured to disable `dd` ibs, obs, iflag, oflag and conv options". Expecting a `makeself` to work at all with a thusly neutered `dd` seems... optimistic.

https://busybox.net/downloads/BusyBox.html
https://git.busybox.net/busybox/tree/coreutils/dd.c#n39

**Comment by realtime-neil** [comment]
```

**Comment by droberg** [comment]
> @droberg I don't think it's fair to say "Busybox" when what you mean is "Busybox configured to disable `dd` ibs, obs, iflag, oflag and conv options". Expecting `makeself` to work at all with a thusly neutered `dd` seems... optimistic.
> 
> https://busybox.net/downloads/BusyBox.html
> https://git.busybox.net/busybox/tree/coreutils/dd.c#n39

Right, I missed this.

**Comment by droberg** [comment]
> @droberg , who made your `busybox`? By way of comparison, this is what the `dd` from `busybox-static` looks like on Ubuntu Xenial:
> 
> ```
> $ apt-cache policy $(dpkg -S $(command -v busybox) | cut -d: -f1); busybox dd -h 
> busybox-static:
>   Installed: 1:1.22.0-15ubuntu1.4
>   Candidate: 1:1.22.0-15ubuntu1.4
>   Version table:
>  *** 1:1.22.0-15ubuntu1.4 500
>         500 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
>         500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
>         100 /var/lib/dpkg/status
>      1:1.22.0-15ubuntu1 500
>         500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
> BusyBox v1.22.1 (Ubuntu 1:1.22.0-15ubuntu1.4) multi-call binary.
> 
> Usage: dd [if=FILE] [of=FILE] [ibs=N] [obs=N] [bs=N] [count=N] [skip=N]
> 	[seek=N] [conv=notrunc|noerror|sync|fsync]
> 
> Copy a file with converting and formatting
> 
> 	if=FILE		Read from FILE instead of stdin
> 	of=FILE		Write to FILE instead of stdout
> 	bs=N		Read and write N bytes at a time
> 	ibs=N		Read N bytes at a time
> 	obs=N		Write N bytes at a time
> 	count=N		Copy only N input blocks
> 	skip=N		Skip N input blocks
> 	seek=N		Skip N output blocks
> 	conv=notrunc	Don't truncate output file
> 	conv=noerror	Continue after read errors
> 	conv=sync	Pad blocks with zeros
> 	conv=fsync	Physically write data out before finishing
> 	conv=swab	Swap every pair of bytes
> 
> N may be suffixed by c (1), w (2), b (512), kD (1000), k (1024), MD, M, GD, G
> ```

My busybox is yocto/opeembedded more or less default. Even if it's possible to rebuild it with the neessary settings I wouln't be surprised it others run in to the same. 

However, it does work with small modifications. Perhaps having a "handle broken busybox" flag would make sense?

**Comment by Kevin0626** [comment]
Hi, in our use case our self-installing package is distributed to other users for their platforms. so we hope it can be adaptable as much as possible.

**Comment by realtime-neil** [comment]
If it's a choice between implementing `dd` compliance checking or ripping out `dd` options that busybox likes to disable, I prefer the latter. What happens to the binary format if we stop zero-padding blocks? What happens to the progress bar and the options that control it? Is there an impact on write performance? If so, how much? Do we care?

**Comment by realtime-neil** [comment]
@droberg, the new flag you propose to work around busybox dd weirdness --- how would you implement it? Is the flag passed during archive creation or archive extraction?

**Comment by droberg** [comment]
> how would you implement it? Is the flag passed during archive creation or archive extraction?

Extraction, I think. I haven't though trough the implications though.
