### ISSUE TITLE
makeself 2.4.0: "--noprogress" error (extracting to/from directories/path/archive name containing spaces)

### ISSUE THREAD

**Issue by sarether** [megastep/makeself#163]
makeself 2.4.0, bash 5.0

Making a makeself archive with this command line:
`./makeself.sh --nocomp --noprogress DIR DISTR_PACKAGE.sh DISTR_NAME ./START_SCRIPT.sh`
or:
`./makeself.sh --xz --nomd5 --nocrc --nox11 --noprogress DIR DISTR_PACKAGE.sh DISTR_NAME ./START_SCRIPT.sh`
etc.

Run installer in directory with spaces in path:
```
Verifying archive integrity... All good.
Uncompressing DISTR_NAMEexpr: non-integer argument
expr: non-integer argument
xz: (stdin): File format not recognized
 ... Extraction failed.
Signal caught, cleaning up
```
Without "--noprogress" option (or running DISTR_PACKAGE.sh in directory without spaces in path) everything is fine.

//EDIT
Fixed in makeself-master 20 February 2019

**Comment by realtime-neil** [comment]
@megastep, I propose closing this because the bug responsible has been fixed.
