### ISSUE TITLE
temp directory is not removed when using --notemp

### ISSUE THREAD

**Issue by arossert** [megastep/makeself#166]
When using the `--notemp` flag to prevent the use of `/tmp`, the extracted directory is not deleted at the end of the run.

Is there a way to not use `/tmp` and remove the temp directory after the execution has finished (successfully or with error).

**Comment by megastep** [comment]
This is intentional behavior. You could try to make this happen through the embedded script you provide for the archive, although that sounds dangerous.

**Comment by arossert** [comment]
@megastep my issue is with a system that set `noexec` flag on `/tmp`, this prevents the execution of makeself by itself, so I added the `--notemp` flag and it is working perfectly but it leaves the temp dir in the running directory.
Is there any option to not use `/tmp` and still delete the extracted directory?

**Comment by megastep** [comment]
In that case, the easiest would simply be to set the `TMPDIR` environment variable to a location that you have proper write access to before you attempt to extract the archive.

**Comment by arossert** [comment]
@megastep Thanks for the advice
