### ISSUE TITLE
Space in license path results in fail

### ISSUE THREAD

**Issue by davidhealey** [megastep/makeself#167]
Using --license I have a path with spaces. It ends up as an invalid path even though I'm escaping the space with \ (I also tried with quotes).

**Comment by realtime-neil** [comment]
@davidhealey does https://github.com/megastep/makeself/pull/168/commits/70b24b4f81bb9cf642533cffe140b76c42a53036 work for you?

**Comment by davidhealey** [comment]
Thanks, that seems to work :)
