### ISSUE TITLE
Can path to run file be determined in setup script?

### ISSUE THREAD

**Issue by smalers** [megastep/makeself#169]
I am using version 2.2.0 on Debian.  This is perhaps a question and maybe a feature request.

I am writing a setup script where the first thing it does is print useful information including the current version what is the version that will be installed by completing the setup.  I want the run script to print this information and a short checklist of things to do before installing (backup previous system, etc.).  However, I don't know how to determine the version that is currently being installed from the run file.   I can run with --info to get useful information but don't know how to find the run file to do that!  If I put `printenv` in the setup script I see environment variable `OLDPWD` being set to the directory where the run script was started, and `_` (underscore) being set to the name of the run file so I'll try to use that.  However, it would be helpful if the makeself installer could set an environment variable that clearly indicated the run file so that the custom setup script could access that and extract information.

**Comment by megastep** [comment]
I think it could be useful to have a future new feature to set environment variables for installer scripts. It's just not the case right now. Using `$_` or `$0` to infer the file name might be your best bet for now if you want to do things this way, but a simpler, more reliable way to do this would simply to include the version inside of your archive. I typically do that in a `VERSION` file that can be easily loaded.
