### ISSUE TITLE
makeself 2.4.0 extract file without read permission for others

### ISSUE THREAD

**Issue by xmeng1** [megastep/makeself#170]
Makeself 2.4.0 extract file without reading permission for others

The makeself is installed by Fedora `dnf install makeself`

After using the old version 2.1.5, the permission is right with reading permission for others.

It seems like not execute `chown` after extracting the files:

![Selection_009](https://user-images.githubusercontent.com/5753142/63764873-b5728200-c8bf-11e9-884a-557e7154449c.png)

makeself command

```
makeself --lsm xxx.lsm ../Output/deployfolder ../Output/xxxx-${1}.bin "xxx Installer" ./setupxxx.sh
```

**Comment by realtime-neil** [comment]
@xmeng1 , which user(s) created the contained files, created the archive, and executed the archive? If `root` created the archive and ran it, then the extracted contents would preserve `root` ownership.

**Comment by xmeng1** [comment]
oh, got it. we use root to run but we have a script to handle user permission, it seems like the script has a problem. The strange thing is version 2.1.5 works but after upgrade to any version above that lead to this issue. 

Let me close the issue firstly if I find other clues and continue it.

**Comment by realtime-neil** [comment]
@xmeng1 , I believe you're correct. With regard to extraction, both the `chown` behavior and the `--nochown` option were recently tweaked. This affects those who, like yourself, rely on `root` to create, populate, and/or extract a `makeself` payload.

**Comment by xmeng1** [comment]
@realtime-neil, yes I noticed the changelog from the 2.2.0 has a new feature of `nochown`.  Our current solution is just to revert the version to the 2.1.5.
