### ISSUE TITLE
Support reproducible builds of makeself archives.

### ISSUE THREAD

**Issue by bracketttc** [megastep/makeself#172]
## Problem

There should be a simple flag to support reproducible builds.

## Current state

Right now, to get a reproducible build, you have to specify a packaging date, specify an overriding mtime to tar in the extra args and choose an appropriate compression option.

`bzip2`, `compress`, `lz4`, and `xz` compression options appear to work without modification. `--nocomp` also works.

If you choose to use gzip, you have to add `-n` to the `GZIP_CMD` variable to omit the name and timestamp of the temporary tarball. This metadata adds no value to makeself, as long as the `-n` flag is supported across all deployment platforms, I think it should be added.
`pigz` does not understand the `-n` flag the same way and appears to still embed the timestamp.

`lzo` embeds timestamps and filenames without an option to strip this information out. There are options to ignore them upon decompression, but the information is unconditionally placed in the archive. [Debian issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896520)

Did not evaluate `gpg` options or `pbzip2`.

## Proposal

Suggest a `--reproducible` flag that, at a minimum, adds `--mtime=1970-01-01` or the date specified by the user in `--packaging-date` and chooses a compression method that does not store timestamps.

Since tar storage order depends on the [underlying filesystem](https://wiki.debian.org/ReproducibleBuilds/Howto#Files_in_data.tar_depends_on_filesystem_order), if tar > 1.28, tar arguments should also include `--sort=name`.

**Comment by bracketttc** [comment]
A reproducible makeself archive can be created without any code changes with:
```
$ makeself.sh --bzip2 \
--tar-extra '--owner=root --group=root --mtime=1970-01-01' --packaging-date ""' \
ARCHIVE_DIR \
"Archive Name" \
./install.sh
```

Performed on my RHEL7 workstation which has tar 1.26 and does not support `--sort`.

**Comment by realtime-neil** [comment]
@bracketttc , it's quite a bit worse than that: #159 

the tldr is that, even between patch releases of gnu tar, the binary output format is not preserved. You can force it, but that requires gnu extensions.

**Comment by realtime-neil** [comment]
Btw, we already have stable sort order.

**Comment by bracketttc** [comment]
I saw that later. And you manage it in a way that is compatible with archaic versions of tar. :smile:

Reproducibility is relative. I understand that there's no real chance of getting a build that is binary identical across years of changes and multiple operating systems. However, running the same software on similar hardware, we should be able to get the same binary out.

We can make steps toward that. As I mentioned in my issue, and you mention in that other issue's thread, `gzip`'s `--no-name` option would strip out the superfluous archive name and mtime. You've got a stable sort order for files input to `tar`. Additional arguments to `tar` like changing owner are good in that they strip out the username of the person preparing the archive. Scripting could remove the original command-line or at a minimum sanitize it somewhat through the use of `basename` to strip out the full path.

**Comment by realtime-neil** [comment]
I think a `--compress-extra` is an idea whose time has come. When and if I ever get back to my refactoring, I'd like to make room for arbitrary options to the compression tool.
