### ISSUE TITLE
Empty folders not included in compressed archive in version 2.4.0

### ISSUE THREAD

**Issue by blindenvy** [megastep/makeself#175]
Version `2.4.0` does not include empty folders in the bin. Versions `2.3.1` or `2.3.0` do not exhibit this problem.

**Comment by bracketttc** [comment]
https://github.com/megastep/makeself/blob/56c742bd90ebcb22feaff4d78ae4e62e72ffc7ad/makeself.sh#L595-L598
The `find` invocation here excludes directories, so the current version only gets directories incidentally -- similar to git.

**Comment by realtime-neil** [comment]
As the author of that behavior, and speaking only for myself, I prefer deterministic archives over empty directories. Maybe others prefer otherwise.

**Comment by blindenvy** [comment]
It's fine if you want to close this as working as intended, however this is a breaking change for people upgrading, and as such you should call out the change of behavior in the version history for the version in which it was introduced.

**Comment by blindenvy** [comment]
Should call out in the version change history when support was removed and when it was added back in.
