### ISSUE TITLE
Syntax error on OLD versions of bash

### ISSUE THREAD

**Issue by rbcrwd** [megastep/makeself#196]
On exhilaratingly old versions of bash (e.g., 2.x on Solaris 10), the syntax `FOO=bar; export FOO` is only incidentally supported when followed by a blank line.

Commit 3cd33e2f introduced such a bug by perpetuating the pattern introduced in 10fa357b, which itself hadn't triggered as a bug yet since it was followed by a blank line.  The following is the unfortunately verbose way to correct this issue.

```diff
diff --git a/makeself-header.sh b/makeself-header.sh
index 5d7bbd1..dc3555d 100755
--- a/makeself-header.sh
+++ b/makeself-header.sh
@@ -12,8 +12,10 @@ CRCsum="$CRCsum"
 MD5="$MD5sum"
 SHA="$SHAsum"
 TMPROOT=\${TMPDIR:=/tmp}
-USER_PWD="\$PWD"; export USER_PWD
-ARCHIVE_DIR=\$(dirname \$0); export ARCHIVE_DIR
+USER_PWD="\$PWD"
+export USER_PWD
+ARCHIVE_DIR=\$(dirname \$0)
+export ARCHIVE_DIR
 
 label="$LABEL"
 script="$SCRIPT"
```

**Comment by megastep** [comment]
Thanks for this, I just committed your fix.

**Comment by rbcrwd** [comment]
I also just realized that `$(...)` style command expansion is a bashism and doesn't work on true Bourne shells. Shall I open a separate bug?

**Comment by megastep** [comment]
No need, I just committed a fix.
