### ISSUE TITLE
the content of license file is not shown

### ISSUE THREAD

**Issue by benzwt** [megastep/makeself#197]
My license file is lic.txt.
I built the installer as follows:
`./makeself.sh --nox11 --license lic.txt package/ ./package.run "installer" ./installer.sh`

After running the ./package.run
The license message shows 'lic.txt' (the file name of the license file) instead of the content of lic.txt.

**Comment by megastep** [comment]
Yeah there seems to be some inconsistency in the way this works in the code? It is supposed to take a file but never actually loads in contents.

**Comment by megastep** [comment]
This should be fixed now.
