### ISSUE TITLE
Going from 2.1.5 to 2.4.0 makes the package double the size

### ISSUE THREAD

**Issue by WaldemarH** [megastep/makeself#199]
Hi guys.

First thanks for the good product, it makes our life much easier. :)

Now when we use 2.1.5 version our package comes out at aprox. 269MB in size.
But if we change to 2.4.0 (with no other difference whatsoever) the package comes out as 523MB.
The strange thing is that extracted directory size comes out at 362MB. I've even tried to pack
the same folder with WinRar and it comes out at 225MB.

So there must be something strange with 2.4.0. Now we like the CRC check so we would like to use 2.4.0, but for now the package size makes this not possible.

Any insight or help would really be appreciated.

Best regards
Waldemar

**Comment by megastep** [comment]
It sounds like maybe you're using a different type of compression? gzip is usually the default but there are other more efficient though less standard like bzip2. So you should check which you are using with your archives.

**Comment by WaldemarH** [comment]
Hi Mega

Thanks for the reply.
Now as said everything is exactly the same where the original and 2.4.0 both have --bzip2 flag defined.

So it's not the compression flag.. has to be something else. :(

Any other idea?

Br
Waldemar

**Comment by realtime-neil** [comment]
@WaldemarH , do you have a minimal reproducer that you can share with us?

**Comment by WaldemarH** [comment]
I'll try to make something... I'll do it tomorrow as for today I'm fully booked already.

**Comment by WaldemarH** [comment]
Hi Neil

Sorry for late response.. got sick.

Anyway here is the link to OneDrive that contains both versions: [OneDrive](https://1drv.ms/u/s!AulAg7BeKIMXgrE09g9WgBlGUe8RCA?e=zj6WJ1)

We use exactly the same command:
`${makeself} ${builddir} ${installation_file}.run 'Nevron IPTV Solution' ./install.sh --bzip2`

And the only difference is that we change the makeself variable from:
makeself = scripts/makeself-2.1.5/makeself.sh
to
makeself = scripts/makeself-2.4.0/makeself.sh

Happy hunting. :)

Br
Waldemar

**Comment by WaldemarH** [comment]
Also if you want me to do any test, just ping me and I'll do them.

BrW

**Comment by megastep** [comment]
Well that is certainly odd behavior, but a couple of quick observations:
- Looking at how you invoke `makeself` to build the archive, if you use `--bzip2` as the last argument it will be considered an argument for your install script, and not actually be used to indicate bzip2 compression with Makeself. You should make it your first argument if that is what you want.
- I tried to recreate your archive with the current code in git and it does appear to function properly, so it's possible that whatever behavior you saw in 2.4.0 was actually resolved by now.

I would guess that somehow the tar data was appended twice to the 2.4.0 version for you, it would just get ignored anyway but that's really quite weird. In any case, it was probably using gzip compression, not bzip2 as your would expect (though that's probably not the issue here).

**Comment by realtime-neil** [comment]
@megastep @WaldemarH , both archives definitely using gzip compression, as shown by the binwalk output I've attached to this comment.

[make-2.1.5.run.binwalk.txt](https://github.com/megastep/makeself/files/4232157/make-2.1.5.run.binwalk.txt)

[make-2.4.0.run.binwalk.txt](https://github.com/megastep/makeself/files/4232158/make-2.4.0.run.binwalk.txt)

There's also a startling quantity of zip and assorted other file types appended after the embedded gzip data. @WaldemarH any idea what that's about?

**Comment by WaldemarH** [comment]
Hi guys.

Thanks for responses. Now as I've inherited old installer I'm currently in learning curve also.

@megastep I'll definitely move the flag forward.
@realtime-neil I have no clue.. the installer works as:
1. phing is started and data is copied to a tmp folder and then modified slightly
2. phing then starts makeself to create an installer that starts the install script

Now I've checked and the tmp folder doesn't contain any zip files and also packaging is executed just before the step that deletes the tmp folder.

`    
    
    
    <target name="package" depends="installer">
        <echo msg="Create portal installable package ..." />
        <chmod file="${makeself}" mode="0755"/>
        <exec command="${makeself} ${builddir} ${installation_file}.run 'Nevron IPTV Solution' ./install.sh --bzip2" checkreturn="true" logoutput="true"/>
        <echo msg="Files packaged OK!" />
    </target>

    
    
    
    <target name="dist" depends="package">
        <mkdir dir="${srcdir}/dist"/>
        <echo msg="Removing temporary files used ..." />

        <delete includeemptydirs="true" dir="${builddir}"/>

        <echo msg="Release package OK!" />
        <move file="${srcdir}/${installation_file}.run" todir="${srcdir}/dist" />

        <echo msg="Done."/>
    </target>
`

Also I can not find these files anywhere on the build machine so I have no clue what they are.
Can you see if they get extracted and where too? Or is there a way to extract them? .... with --noexec and --target xxx I get just the standard files.

Now as the company has an issue with one worker that installed various crap on all kinds of machines, hopefully this is not something in that line. :/

BrW

**Comment by WaldemarH** [comment]
Anyway just a side question.. what is the best compression flag?

**Comment by WaldemarH** [comment]
I've done the --bzip2 flag test and it's the same.. the 2.1.5 creates 270MB-ish file where 2.4.0 510MB-ish.

**Comment by realtime-neil** [comment]
> @megastep I'll definitely move the flag forward.
> @realtime-neil I have no clue.. the installer works as:
> 
>     1. phing is started and data is copied to a tmp folder and then modified slightly
> 
>     2. phing then starts makeself to create an installer that starts the install script
> 
> 
> Now I've checked and the tmp folder doesn't contain any zip files and also packaging is executed just before the step that deletes the tmp folder.

I suspect that this temporary directory is dirty. Have you tried performing the invocation to `makeself` by "hand", as it were? Can you comment out the `<delete>` element? That would allow you to obselve the contents of the temporary directory after it has been populated by the build system.

**Comment by realtime-neil** [comment]
@WaldemarH , I extracted and re-compressed your `make-2.4.0.run` archive. Here's how I did it:

```
$ ./make-2.4.0.run --noexec --target ./make-2.4.0 && \
> ~/code/makeself/makeself.sh ./make-2.4.0 ./redo-make-2.4.0.run 'Redo Nevron IPTV Solution' ./install.sh
```

Here's a comparison between the your original and my redo:
```
$ ls -lah make-2.4.0.run redo-make-2.4.0.run 
-rwxrwxr-x 1 neil neil 518M Feb 20 16:27 make-2.4.0.run
-rwxrwxr-x 1 neil neil 266M Feb 20 22:50 redo-make-2.4.0.run
```

This is a strong indication that the environment in which you're building these archives is somehow tainted. For reference, I'm using the `HEAD` of `master` of `makeself`; i.e., as of this writing, 23f49fa4d4c98204376fbdfdb8d9c0a8b1a3bf10 .

**Comment by WaldemarH** [comment]
Hi guys

Thanks for all the info. I have tested build on my own VM and all is good, so we decided that we'll just create a new build VM and ditch old one.. as it looks it was modified somehow by the @#$@#$!@$ worker.

Anyway I have another question... as I've modified the installer builder and now I'm starting the makeself in a script I'm getting to shell the list of files that are being packaged. But I don't want that.. I want it to be silent. Unfortunately I --help didn't show any 'be silent' flag. So I've tried:

`	./scripts/makeself-2.1.5/makeself.sh --bzip2 ./tmp "/var/www/html/nightly/manager/${installation_file}.run" 'Nevron IPTV Solution' ./install.sh > /dev/null`

But it didn't help... I assume the '> /dev/null' is used as a './install.sh' parameter.

Any advice how to make it silent?

Best regards
Waldemar

**Comment by megastep** [comment]
It would not be a parameter, however you should try to redirect stderr instead, using `2> /dev/null`  or even `> /dev/null 2>&1` to redirect both.

**Comment by WaldemarH** [comment]
Hi Mega

The stderr redirect works ok, but now I can not check the return value. 

Anyway in 2.1.5 I've added '-q' to bzip2 flags and now it's working as it should. On 2.4.0. hopefully '--quiet' flag will do the trick (still waiting for admin to create a new build machine).

Thanks again guys.

Have a nice year. :)

Br
Waldemar
