### ISSUE TITLE
Is cleanup script logic in header correct???

### ISSUE THREAD

**Issue by hazendaz** [megastep/makeself#205]
```
        eval "\"\$cleanup_script\" \$scriptargs \$cleanupargs"
```

The above seems like a copy/paste error.  Why are both scriptargs and cleanupargs passed here?  I think script args was a mistake...please confirm...

**Comment by megastep** [comment]
Mmh, I think you might be right. @asoc wrote that code - want to chip in ?

**Comment by asoc** [comment]
It was intentional, my cleanup scripts make use of the arguments given at build time.

If there is a use case to not have them I can add a toggle with default behaviour being whichever is preferred.

**Comment by megastep** [comment]
I guess I'm fine with that as long as it's properly documented. Also maybe the cleanup args should come first?

**Comment by asoc** [comment]
To me it makes more sense to have `scriptargs` come first, as they are static and well known at runtime so both the exec and cleanup scripts can easily handle/ignore them. If they were to come afterwards I think it would make parsing a bit more of a headache, and you then have two different behaviours for similar processes.

That said, your repo your rules. Let me know which way you'd prefer and what the default behaviour should be (with or without `scriptargs`)

**Comment by hazendaz** [comment]
Thanks for confirming.  I'll post a link to code for the maven plugin once I push it up with notes on how I think this works.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by megastep** [comment]
I actually don't have a strong opinion on the subject, and if it works for your use cases I would just leave it as is for now.
