### ISSUE TITLE
Support Zstd compression tools

### ISSUE THREAD

**Issue by EscapeLife** [megastep/makeself#210]
> **👻 I want to be able to add support for Zstd to the tool, thanks you!**

Zstandard is a real-time compression algorithm, providing high compression ratios. It offers a very wide range of compression / speed trade-off, while being backed by a very fast decoder (see benchmarks below). It also offers a special mode for small data, called dictionary compression, and can create dictionaries from any sample set. Zstandard library is provided as open source software using a BSD license.

- `https://facebook.github.io/zstd/`
- `https://github.com/facebook/zstd`

I did a compression test on the docker image, as shown below:

```bash
# The original file => (4.2G)
-rw------- 1 escape escape 4.2G Feb 21 15:18 docker_app_0.0.1.tar

# makeself gzip => (2.0G)
-rwxr-xr-x 1 escape escape 2.0G Feb 21 15:31 docker_app_0.0.1.run

# zstd => 37.98% => (1.6G)
-rw------- 1 escape escape 1.6G Feb 21 15:38 docker_app_0.0.1.zst
```

**Comment by megastep** [comment]
It should be easy enough to implement, like the other compression methods we already support.

**Comment by EscapeLife** [comment]
@megastep Thank you very much. Good health for you 👍🏼

**Comment by megastep** [comment]
I just added basic support for zstd compression. You can even pass the compression level as required. Seems to work on all platforms. Thanks for the tip!

**Comment by EscapeLife** [comment]
@megastep 👍👍👍 and the repo README.md and https://makeself.io/ document not updated.

**Comment by megastep** [comment]
Yeah I'm probably gonna need to make an official release first but I'll get to it. We're overdue for one anyway.

**Comment by EscapeLife** [comment]
ok👌
