### ISSUE TITLE
Parameter to block the unsigned binary

### ISSUE THREAD

**Issue by springleo** [megastep/makeself#211]
Hi,

I am wondering if there is already a parameter that checks if the binary itself is signed, with a known key on its target server? If not, just fail or exit.

Something like "--sha256"

Please advise, thanks in advance.

**Comment by megastep** [comment]
I'm not sure if that's exactly what you mean, but yeah by default the internal binary's checksums are stored to check that it is uncorrupted. I realize this is is not the same thing as a real signature but we do store at least CRC and MD5 checksums, with SHA256 being optional.

**Comment by megastep** [comment]
There is an `--sha256` argument for that purpose, incidentally.

**Comment by springleo** [comment]
Sorry, for not being clear. We would like our binaries to be built with corporate digital signatures. We use makeself tool to build a self extracting binary. Currently, when the binary is triggered, the first thing it does is to check the sha256sum of the binary, thanks to "--sha256" flag. However, as per the org wide compliance guidelines, that would not suffice. Before executing a binary, it needs to be verified with a proper signatures, confirming the origin of the software. 

In this light, wondering if there can be (or already is) a parameter viz. "--gpg -verify" 

Thanks in advance.

**Comment by megastep** [comment]
There is actually some basic GPG support right now with the `--gpg-encrypt` and `--gpg-extra` arguments which may be able to do what you want. I think currently it uses encryption instead of compression but maybe that would work for your purpose.

**Comment by springleo** [comment]
Figured an alternative way of doing this using openssl command, closing the thread. Thank you for kind support.

**Comment by jjvbsag** [comment]
@springleo Can you share your solution?
Regards
