### ISSUE TITLE
makeself adds hard links to the archive

### ISSUE THREAD

**Issue by jjvbsag** [megastep/makeself#214]
To reproduce I created a short shell script

```sh
#!/bin/bash
export LANG=C
#
# get master
#
test -f makeself-master.zip || \
wget -O makeself-master.zip https://github.com/megastep/makeself/archive/master.zip

#
# extract
#
rm -rf makeself-master
unzip makeself-master.zip

#
# create sample dir
#
rm -rf sample-dir
mkdir -p sample-dir
echo "file1" > sample-dir/file1.txt
hexdump -C sample-dir/file1.txt > sample-dir/file1.dmp
echo "true" > sample-dir/install.sh

#
# create run file
#
rm -rf sample.run
makeself-master/makeself.sh sample-dir sample.run "Sample" install.sh

#
# check content
#
./sample.run --list
```

Output of list command is
```
Target directory: sample-dir
drwxrwxr-x itsme/itsme   0 2020-06-05 13:32 ./
-rw-rw-r-- itsme/itsme   5 2020-06-05 13:32 ./install.sh
-rw-rw-r-- itsme/itsme   6 2020-06-05 13:32 ./file1.txt
-rw-rw-r-- itsme/itsme  78 2020-06-05 13:32 ./file1.dmp
hrw-rw-r-- itsme/itsme   0 2020-06-05 13:32 ./file1.dmp link to ./file1.dmp
hrw-rw-r-- itsme/itsme   0 2020-06-05 13:32 ./file1.txt link to ./file1.txt
hrw-rw-r-- itsme/itsme   0 2020-06-05 13:32 ./install.sh link to ./install.sh
```

I believe, this was introduces by commit 
https://github.com/megastep/makeself/commit/e242ff1de6d9dc1dde2143745add49df95ff95ee

If I drop the ` -o -links 2` by adding
```sh
perl -pi -e s'/-o -links 2//;' makeself-master/makeself.sh
```
to above script after the extract section, the archive is fine
```
Target directory: sample-dir
-rw-rw-r-- itsme/itsme   5 2020-06-05 13:36 ./install.sh
-rw-rw-r-- itsme/itsme   6 2020-06-05 13:36 ./file1.txt
-rw-rw-r-- itsme/itsme  78 2020-06-05 13:36 ./file1.dmp
```

---
My System information:
```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

**Comment by realtime-neil** [comment]
What is the desired behavior, that files with more than one hard link are excluded while empty directories are included?

**Comment by jjvbsag** [comment]
@realtime-neil I don't know, what the desired behavior of the commit was.

_My_ desired behavior is, that makeself behaves similar to a normal tar archive, just adding the option to run an install script. (and some other nice things). And makeself did so before that commit.

**Comment by realtime-neil** [comment]
@jjvbsag Okay, let's get into the weeds here and consult some documentation.

* https://www.gnu.org/software/tar/manual/html_node/hard-links.html
* https://www.unix.com/man-page/linux/1/tar/
* https://www.unix.com/man-page/freebsd/1/tar/

Can you be specific with regard to what you consider "normal" vis-a-vis the `-l`,`--check-links` option? With so many `tar`s out there, it's non-trivial to pin down what "normal" means.

**Comment by realtime-neil** [comment]
Whoops, nevermind, I see what you mean --- that's weird.

**Comment by jjvbsag** [comment]
Ok, I tested a bit more and found, using `-o -empty` instead of  `-o -links 2` also created the desired behaviour - including empty dirs -  but without the error of adding hardlinks.

The only thing, I cannot verify is, if `-empty` as option for find is available on all target platforms.

**Comment by megastep** [comment]
I don't see it in the list of options for the BSD version at least. It might be a GNU thing.

**Comment by realtime-neil** [comment]
This would be closed by https://github.com/megastep/makeself/pull/223
