### ISSUE TITLE
Cannot link to makeself "Unable to open header file: makeself-header.sh"

### ISSUE THREAD

**Issue by metaturso** [megastep/makeself#215]
It's unclear from the site/manual and README how a Makeself 2.4.2 release as downloaded from GitHub is to be installed.

I'm using `update-alternatives` to create a link to `/opt/makeself-2.4.2/makeself.sh` in `/usr/local/bin`, but when running Makeself I keep getting this error:

```bash
Unable to open header file: /usr/local/bin/makeself-header.sh
```

I wonder if there's a preferred way to install Makeself instead that doesn't involve copying all of Makeself's scripts into my `$PATH`.

**Comment by megastep** [comment]
Well I'm not sure how people have usually packaged Makeself, but by default `makeself.sh` looks for `makeself-header.sh` in the same directory as itself, so that's what you get there. Easiest would just be to copy it in `/usr/local/bin` there, even though it is not technically an executable.

**Comment by metaturso** [comment]
Yes, I could already see that much from the code. I was hoping you'd see the problem and suggest a way we can make [`makeself.sh:L213`](https://github.com/megastep/makeself/blob/master/makeself.sh#L203) work when `makeself` itself is linked.

But nevermind, I'll just keep patching it manually. Thanks for nothing chap.

**Comment by megastep** [comment]
Hey I never really designed this tool to become a system-level package. Over the years others have packaged it for Debian, brew, etc. It hasn't been a focus for me as it was always more of an internal tool. That said, if I were to take steps toward this, I would probably have it more explicitly look for the header file in a fixed location, like `/usr/share/makeself` or something like that.

I'm more than open to patches and it's not a big change. It's just hasn't been a priority for me.
