### ISSUE TITLE
Append appears to be broken

### ISSUE THREAD

**Issue by andyneff** [megastep/makeself#216]
I'm running master 39da42d6d07d976c6997909678be821410cb81ff and `--append` does not appear to be working. (Also tried 2.4.2)

## Steps to reproduce

1. I create an archive `makeself.sh ./somedir archive.sh label_me ./myscript`
2. I append to it `makeself.sh --append ./new_files archive.sh`

## Error observed

When the second makeself.sh call is made, I see this on the output:

```
About to compress 88 KB of data...
Adding files to archive named "./dist/just"...
tail -n + ./dist/just
tail: invalid number of lines: ‘+’

gzip: stdin: unexpected end of file
```

Which comes from [this](https://github.com/megastep/makeself/blob/39da42d6d07d976c6997909678be821410cb81ff/makeself.sh#L632) line, where `OLDSKIP` is undefined.

I can see in the history, that `OLDSKIP` used to be `SKIP`+1. but it was removed recently, but that was only in dumpconf, so I'm not sure how to fix this.

I tried adding SKIP+1 myself, but sometimes its +1, sometimes its +2 (verified in `vi`)

## Tests

The unittest `appendtest` actually has the same problem

```
Adding files to archive named "makeself-test.run"...
tail: invalid number of lines: ‘+’

gzip: stdin: unexpected end of file
```

Checking `--check` doesn't actually detect that the previous files were all deleted. Some for the other compression algorithms

## Desired outcome

Append should work

**Comment by megastep** [comment]
Odd - what OS are you on?

**Comment by andyneff** [comment]
I'm running Fedora 31, but I can try another OS in docker if you have one I should check out?

**Comment by andyneff** [comment]
- About the +1 or +2 comment, the value of `skip` in the header of the archive `+ 1` is consistently the right line number.

**Comment by megastep** [comment]
Right, that's what it should be. I'm just wondering it there's something about your environment that would make this line count disappear somehow.

**Comment by andyneff** [comment]
I can see no where in the source code where `OLDSKIP` is set

**Comment by megastep** [comment]
Yeah I'm seeing that too. That sounds like the cause of this, checking when that variable went away...

**Comment by andyneff** [comment]
According to my debugger, I think the value of skip we need is stored in `OLDENV`?

This was the commit I found there it was mentioned. Not sure how they were connected: https://github.com/megastep/makeself/commit/0d093c01e06ee76643ba2cffabf2ca07282d3af1

**Comment by andyneff** [comment]
Oh, I see. [This](https://github.com/megastep/makeself/blob/master/makeself.sh#L463) line used to set the `OLDSKIP` that used to be part of `--dumpconf`

**Comment by megastep** [comment]
Also our unit tests for append are obviously broken :(

**Comment by andyneff** [comment]
I think they are testing the archive is "good", but not that they have all the files. The archive _is_ valid, so I'd just call them "not sufficient" :)

**Comment by andyneff** [comment]
Adding 
```
OLDSKIP=`expr $SKIP + 1`
```

After line https://github.com/megastep/makeself/blob/master/makeself.sh#L463 works

**Comment by megastep** [comment]
It does work but it seems like instead of appending it is just overwriting the archive still, losing the previous contents.

**Comment by andyneff** [comment]
Hmmm, that fix successfully appends for me...
