### ISSUE TITLE
Setting in Stop via TCSAFLUSH for stdin failed! - tcsetattr (5: Input/output error)

### ISSUE THREAD

**Issue by kietheros** [megastep/makeself#220]
I generate a self-extractable file to install my software on Ubuntu server. The startup script contains some simple commands
`    apt install screen -y  
    apt install unzip -y  
    apt install zip -y  
`
If I extract file using --noexec, and run startup script then everything is OK.
But if I run self-extractable file, I got the below error in the first run
`Suggested packages:
                     zip
                        The following NEW packages will be installed:
                                                                       unzip
                                                                            0 upgraded, 1 newly installed, 0 to remove a                                           Setting up unzip (6.0-21ubuntu1) ...
                                                                               Processing triggers for mime-support (3.60ubuntu1) ...
             Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
                                                                  E: Setting in Stop via TCSAFLUSH for stdin failed! - tcsetattr (5: Input/output error)
                                E: Setting in Stop via TCSAFLUSH for stdin failed! - tcsetattr (5: Input/output error)
Reading package lists... Done`

Although, the startup script still runs successfully. the terminal output became messy, wrong line break.
I suspect that option "-y" which is related to terminal control caused this error. And this error only appears at first run on my server.
How can I fix this error ? Thank you !

**Comment by megastep** [comment]
Well that is odd but it's certainly not Makeself calling `tcsetattr` here... To me this looks more like some command you're running (maybe apt here) is looking for a terminal, and it's just not available in that context (probably just redirected to something else, like a pipe).

**Comment by kietheros** [comment]
@megastep If I extract file using --noexec, and run startup script then I didn't get this error. And it only appears in the first run self-extractable file.

**Comment by kietheros** [comment]
@megastep Does the self-extractable file run startup script in background ?

**Comment by megastep** [comment]
no, if you use `--noexec` then it won't run the script at all. It should be the last step when archive extraction completed. No backgrounding involved.

**Comment by kietheros** [comment]
@megastep No, I ask about runing archive file normally. When it runs startup script, I still can enter other commands on the terminal.

**Comment by megastep** [comment]
Well the script is run through an `eval` command after extraction so depending on your shell it may or may not spawn it with a pseudo-terminal attached.

**Comment by kietheros** [comment]
I use Windows Terminal to ssh to Ubuntu Server. The shell is bash, the startup script was run in background, so the above error appeared. Could you suggest me a way to fix or debug more about this error ?

**Comment by megastep** [comment]
If you run in background then certainly the command doesn't have a terminal available to its standard input. I would investigate any command line arguments for apt available to suppress all input/output and make sure to use that. You should not use anything that requires user interaction in that context.

This is not really a Makeself issue so I'm closing this.

**Comment by kietheros** [comment]
@megastep Sorry for my unclear declaration. I don't run any commands in background. The startup script doesn't contain any background commands. The archive created by makeself run startup script in background.

**Comment by kietheros** [comment]
I confirm this is not a makeself issue. In my install script, I had accidentally killed the makeself script. After that, all commands ran in background.
