### ISSUE TITLE
Duplicate entries in 2.4.2 due to PR #176

### ISSUE THREAD

**Issue by rainerjung** [megastep/makeself#222]
The new condition "-type -d -o links 2" introduced in e242ff1  as a fix for issue #175 does not only match empty folders, but also folders that do not contain sub directories (but for instance files). By the recursive default behavior of most tar implementation all files from such leaf folders now get included twice. The archive increse significantly on size.

**Comment by realtime-neil** [comment]
@rainerjung could you show what you mean by way of an example?

**Comment by rainerjung** [comment]
For a reproducer use the following script:

    #!/bin/bash

    name=makeself-reproducer-222

    tmpdir=/tmp/$name
    rm -rf $tmpdir
    mkdir $tmpdir
    cd $tmpdir

    # Checkout makeself
    git clone git://github.com/megastep/makeself.git

    # Create content to archive
    mkdir in
    mkdir in/sub
    i=1000
    while [[ $i -gt 0 ]]
    do
        echo '0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789' >> in/sub/somefile
        i=$((i-1))
    done

    # Show contents to archive
    find in -ls

    # Run makeself
    makeself/makeself.sh --nocomp in archive.sh "$name" ''

    # Show result size
    ls -ld archive.sh

    # Show result contents
    ./archive.sh --list

I ran it on RHEL 6 and got the following result:

The find output for the original directory tree that I archived using makeself:

    1308241    4 drwxr-xr-x   3 esuppbld esupport     4096 Sep 21 09:10 in
    1308242    4 drwxr-xr-x   2 esuppbld esupport     4096 Sep 21 09:10 in/sub
    1308243  100 -rw-r--r--   1 esuppbld esupport   101000 Sep 21 09:10 in/sub/somefile

Note that in/sub is a directory with link count 2. File somefile has a size of around 100KB.

The output of makeself.sh:

    Header is 667 lines long
    
    About to compress 108 KB of data...
    Adding files to archive named "archive.sh"...
    ./sub/
    ./sub/somefile
    ./sub/somefile
    CRC: 181601348
    MD5: b8778a81b86e8ad27d4a1aa60c4b5328
    
    Self-extractable archive "archive.sh" successfully created.

Note that ./sub/somefile is contained twice in the output.

And the listing of the resulting (uncompressed) archive file shows:

    -rwxr-xr-x 1 esuppbld esupport 231851 Sep 21 09:10 archive.sh

and it indeed contains two copies of the file somefile.

This is due to "tar" being called with "./sub" and also with "./sub/somefile". Since tar is recursive by default, calling it with "./sub" already include ./sub/somefile and the following "./sub/somefile" then includes another copy of the file into the archive.

Note that the test results depend on the exact type of file system and tar version one is using. On more modern RHEL versions (7 and 8) I can still see the link count 2, but tar is more clever and transforms the second copy of somefile in the archive into a hardlink:

    drwxr-xr-x esuppbld/esupport 0 2020-09-21 09:20 ./sub/
    -rw-r--r-- esuppbld/esupport 101000 2020-09-21 09:20 ./sub/somefile
    hrw-r--r-- esuppbld/esupport      0 2020-09-21 09:20 ./sub/somefile link to ./sub/somefile

which is better but still wrong. The root cause is the broken "find . ! -type d -o -links 2" in makeself.sh.

**Comment by mhobbs-ibm** [comment]
This change causes archive.sh to break on systems that use a non-GNU version of tar. For example, here's the result of running the `./archive.sh` example above on AIX:
```
$ ./archive.sh
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing     58%  ... Extraction failed.
Signal caught, cleaning up
 100%
```

The problem is that the `tar xp` command produces this output:
```
x ./sub
x ./sub/somefile, 101101 bytes, 198 media blocks.
tar: 0511-174 Cannot link ./sub/somefile to ./sub/somefile: A file or directory in the path name does not exist.
```

**Comment by realtime-neil** [comment]
@rainerjung and @mhobbs-ibm , would you kindly test my proposed patch to see if it addresses the issue and is supported on AIX?

**Comment by realtime-neil** [comment]
@mhobbs-ibm welp, your `find` conspicuously lacks the `-empty` on which my patch depends:

https://www.ibm.com/support/knowledgecenter/ssw_aix_72/f_commands/find.html?view=embed

I'll keep looking for something better.

**Comment by mhobbs-ibm** [comment]
For what it's worth, I build on Linux and execute on AIX, so the missing `-empty` expression wouldn't affect me. But yeah, if you still want to be able to build on AIX, that wouldn't work.

**Comment by realtime-neil** [comment]
Try my latest horribly ugly (but POSIX-`find-`compliant!) solution.

**Comment by megastep** [comment]
I also build on Linux and occasionally ship AIX packages, so it's good somebody is keeping an eye on this. :)
