### ISSUE TITLE
unable to install .run file in arm platform, "Error in checksums: 3937251723 is different from" 

### ISSUE THREAD

**Issue by Gyanaranjan08** [megastep/makeself#225]
HI, 
I am trying to devlope a self extracting tar file (which I want to install on an ARM_linux enviornment) through makeself linux tool on a ubuntu x86 machine.
command : **"/usr/bin/makeself  --nomd5  --nocrc --tar-quietly ../my_program/ my_program.run "arm example  installer" ./startup.sh"**  

successfully generate the file "my_program.run" file .

While trying to install the run file on sdc it is showing checksum error, even though I have generated the installer with --nomd5 options.

" 100%  + sum1=3937251723
+ test x3937251723 '=' x
+ echo 'Error in checksums: 3937251723 is different from '
Error in checksums: 3937251723 is different from
+ exit 2
"
Please help me in solve the issue .

**Comment by megastep** [comment]
Sounds like you might be missing the `cksum` on the ARM machine?

**Comment by Gyanaranjan08** [comment]
"**cksum my_program.run
3401472676 30493377 my_program.run**"  cksum command is working for the mentioned file in my ARM machine.

**Comment by megastep** [comment]
OK, on closer look it looks like it would rather be missing the CRC checksum in the archive itself. What does `./my_program.run --dumpconf` return? What version of Makeself are you using?
