### ISSUE TITLE
Usage of notemp should create similar structure in current directory

### ISSUE THREAD

**Issue by hazendaz** [megastep/makeself#229]
Since notemp isn't creating a timestampted based directory similar to what is done with temp, it is not able to run installs in parrellel.  Its unclear how to make that work with it currently setting it to '.'.  Is there any way around this or can this be fixed to be more in line wiht the /tmp usage?

**Comment by megastep** [comment]
I think `--notemp` intentionally recreates the directory structure that was used when creating the archive. So in that sense using a randomized directory name would make its output unpredictable, which is usually not why people use this option.

**Comment by hazendaz** [comment]
Is there any way to have it general folder in that case just like it would in temp?

The problem we are facing is some security change that no longer allows scripts to be run from /tmp.  In that case, notemp is to get it away from there to where its run from.  We sort of expected it would create a temp directory in that run location but rather it just exploads as is.  So in case we have, we run parrellel builds and it now conflicts.  We worked around it by creating our own temp location but suspect it would make more sense to be done inside makeself usage.

**Comment by megastep** [comment]
We could add something for it but I'm rather reluctant. Why not just creating a temporary folder yourself and extracting the archive inside of it? It's trivial enough to do.

**Comment by hazendaz** [comment]
That is what we ended up doing.  It just seems odd here that when using /tmp, it creates a temporary folder automation but when not using /tmp it does not.  notemp to me sort of inclines it doesn't use /tmp but I guess that is just not the full picture.

**Comment by megastep** [comment]
It's just not the typical use case. Typically temporary directories are used in conjunction with a builtin installation script that will put the files in the right place (the temporary files are then automatically removed). If you use `--notemp` this is more akin to extracting a regular tar archive and keeping its original structure.

**Comment by hazendaz** [comment]
fair enough.  would it make sense to have a property that just performs the temp processing in current directory rather than using /tmp?  Or does this still sound too custom to be addressed here?  Admittedly we are acting to an issue dropped on us without any confirmation its an industry security standard.

**Comment by hazendaz** [comment]
Maybe this additional info will help.

Our previous process..
- copy makeself archive release to /tmp and execute
- content in /tmp space then executed

Both are blocked for us now so we switched to use the user home.  We still want how it worked but just are not being allowed to execute scripts from /tmp at all.

**Comment by hazendaz** [comment]
caveate here, just looking for direction that makes sense and expert guidence on the subject more than anything else.  What makes most sense will be enough for me.

**Comment by megastep** [comment]
Personally in this kind of situation, I would just set the `TMPDIR` env variable before calling the script, so it would be somewhere within the user's directory, i.e. `TMPDIR=~/tpm ./archive.run`

**Comment by megastep** [comment]
This was a common scenario in the days of archives shipped on CDs as their filesystems would often be mounted in a way that didn't allow executables. Another option is to explicitly call sh or bash, which goes around the problem: `bash archive.run`

**Comment by hazendaz** [comment]
Thanks, I like that suggested approach.  Appreciate your time on this.
