### ISSUE TITLE
Cannot extract makeself-2.4.2.run

### ISSUE THREAD

**Issue by nunotexbsd** [megastep/makeself#238]
Hello,

makeself-2.4.2.run fails to extract:

```
sh makeself-2.4.2.run
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Makeself v2.4.2  100%   ... Extraction failed.
Terminated

```
Same result with bash.

How do I debug it so I can see whats wrong?
FreeBSD 12.2 AMD64

Thanks,

Nuno Teixeira

**Comment by megastep** [comment]
I would suggest using the `-x` argument to bash or sh to get a trace of the commands being actually called. Maybe you're having some permissions issue?

**Comment by nunotexbsd** [comment]
sh -x makeself-2.4.2.run [log](https://termbin.com/g4l9)

Could you take a look?

**Comment by megastep** [comment]
Not really clear, but I think that's probably the `tar` command failing on your system.

**Comment by nunotexbsd** [comment]
Looks that other people have same problem:
https://docs.freebsd.org/cgi/getmsg.cgi?fetch=182234+0+current/freebsd-ports

**Comment by nunotexbsd** [comment]
I've tested old releases (2.4.0., 2.3.1, 2.3.0 and 2.2.0) and all extract ok without errors.

**Comment by megastep** [comment]
Interesting. We've had quite a few commits since 2.4.2 was released, so I wonder if that's happening in the current master branch. Would you be able to check it out and tell me if that's the case? I don't think I have a handy installation of FreeBSD though I will check it out.

**Comment by nunotexbsd** [comment]
_Here is also how I created the makeself.run archive which contains the Makeself distribution:

makeself.sh --notemp makeself makeself.run "Makeself by Stephane Peter" echo "Makeself has extracted itself_

Checkout makeself:
`gh repo clone megastep/makeself`
- 2.4.2: OK
`makeself --notemp makeself makeself.run "Makeself by Stephane Peter" echo "Makeself has extracted itself"`
- latest commit: OK
`sh makeself/makeself.sh --notemp makeself makeself.run "Makeself by Stephane Peter" echo "Makeself has extracted itself"
`
Maybe something went wrong when 2.4.2.run was made it?

**Comment by megastep** [comment]
I am able to reproduce this on a fresh FreeBSD 12.2 install. It is weird as it is otherwise working fine archiving/unarchiving on FreeBSD itself. The archive should have been produced on a Linux system (through Github Actions), usually not a problem, so I'm not sure what is going here but I will investigate.

**Comment by megastep** [comment]
I'm also getting the same behavior when downloading the archive from Github and trying to extract on macOS, even though the checksums pass. So I'm wondering if some incorrect tar data is being appended by GNU tar (on Linux) that's not being handled well by BSD tar, and causing this error.

**Comment by megastep** [comment]
Seems to be confirmed; when I just replace `tar` with `gtar` the archive works properly.

**Comment by megastep** [comment]
I think I have a fix; simply using `--posix` with tar when creating the archive produces more compatible archives. I used to build the archives myself on my Mac with BSD tar, and 2.4.2 was built on Ubuntu via CI. So that's probably what brought this up.

I'm going to release 2.4.3 with this change.

**Comment by megastep** [comment]
2.4.3 is out and should fix this issue.

**Comment by nunotexbsd** [comment]
Thank you!
I'm updating archivers/makeself FreeBSD port!

Cheers,
Nuno
