### ISSUE TITLE
Add a pre-extract script

### ISSUE THREAD

**Issue by gowthamgutha** [megastep/makeself#242]
Sometimes we need to do some cleanup before the `.run` file is actually extracted.
For eg, we stop the processes before extracting the files.
In our use-case, not doing so would end up in a system reboot.

So, I would like to propose adding a pre-extract script that gets executed before the extraction takes place.

**Comment by megastep** [comment]
I think this has been suggested before but the main challenge would be where to store that pre-extract script. If it is not embedded in the archive, then it needs to be included somewhere in the prefix header and this can be tricky.

However I wonder if you're just not doing this right - by default your archive should be extracted in a temporary location, not in any place that should overwrite existing files (unless you explicitly use `--target` when extracting).

To me a better solution would be to write the embedded script to do its own installation from the files that have been extracted in the temporary location; indeed this is the way Makeself is more often used. So your script can stop any processes it needs before manually copying the files to the right place. The temporary files are then deleted automatically at the end of your script.

**Comment by Ost3rbaer** [comment]
there is at least one use case not covered by the tmp-directory scenario: automatic installation of the suitable decompressor for the payload, e.g.

zypper in -y --no-recommends zstd (for SuSE)
apt-get install (for Debian+derivates)

**Comment by megastep** [comment]
True, but I wouldn't advise doing something that requires root privileges from within an archive, like installing packages.

**Comment by mpoberezhniy** [comment]
The `--preextract` option has been merged. I assume this issue can be closed. When using the option I would recommend also using `--nomd5` and  `--sha256`, it makes the integrity check a lot faster.
