### ISSUE TITLE
No "more"

### ISSUE THREAD

**Issue by UlyssesHerniosus** [megastep/makeself#245]
Hi,
playing around with github I find it very useful. I have one minor improvement to better support "Git for Windows" bash: Don't call "more" if not available. I wanted to insert a pull request but behind our firewalls accessing github repos is not straightforward. Thus the patch here:

Regards, Ulysses

`commit 1275c30471eb891868d33867968510486f65a6d2 (HEAD -> master, origin/master, origin/HEAD)
    Add option to run without "more" still displaying the license - useful when run using "Git for windows" bash

diff --git a/makeself-header.sh b/makeself-header.sh
index c6cb071..e31447f 100644
--- a/Tools/makeself/makeself-header.sh
+++ b/Tools/makeself/makeself-header.sh
@@ -66,7 +66,11 @@ MS_PrintLicense()
     if test x"\$accept" = xy; then
       echo "\$licensetxt"
     else
\-      echo "\$licensetxt" | more
\+        if [ -x "\$(command -v more)" ] ; then
\+            echo "\$licensetxt" | more
\+        else
\+            echo "\$licensetxt"
\+        fi
     fi
     if test x"\$accept" != xy; then
       while true
`

**Comment by UlyssesHerniosus** [comment]
Hi,
so something like ` if test -x `which more || command -v more || type more` ; then` ? 

Regards, Ulysses

**Comment by megastep** [comment]
Ok, I'm trying to address all this with commit 17ab4ead81e6e7e652fa96e685f830656e2d1b94

**Comment by UlyssesHerniosus** [comment]
Thank you, great! I will integrate with the next release. Until then I have my local adaptions.

Regards, Ulysses
