### ISSUE TITLE
[Makeself 2.4.4] Failed to create temporary archive: /tmp/mkself8387.tar

### ISSUE THREAD

**Issue by bojanbt6** [megastep/makeself#250]
Switching to the latest Makeself 2.4.4 release throws these errors related with tar when creating self-extracting archive:

`ERROR: failed to create temporary archive: /tmp/mkself8387.tar
tar: value 1710904329 out of uid_t range 0..2097151`

It seems the following patches cause this:
- https://github.com/megastep/makeself/commit/a66b36404340b5914c155ecd0624bef5e996793b
- https://github.com/megastep/makeself/commit/b2b116c242a3a3d9cc75b7e4c1c246094fcc423a

If I modify the makeself.sh script file and return back the "--posix" flag all works fine as it worked on the previous release 2.4.3.
I run Makeself 2.4.3 / Makeself 2.4.4. on Ubuntu 18.04.5 & GNU tar 1.29.
Maybe a flag for choosing a tar format should be introduced to addition of the default one?

**Comment by megastep** [comment]
That's odd, I would think the error is coming out of the tar command. Not sure why you have these huge user IDs on your system? Maybe a cleaner way to handle this might be to ignore UIDs altogether.

**Comment by bojanbt6** [comment]
Yes the problem is coming from the tar command, but why it is happening when "--format ustar" is used and not "--posix" it is an interesting question but it is a problem as it cannot be co controlled from Makeself (it is hardcoded there).
The PCs are domain controlled enterprise PCs so hence the large user IDs.
Adding "--no-same-owner" to tar does not help.

**Comment by megastep** [comment]
I'm guessing the `ustar` format had shorter integer sizes for user IDs. I would try passing an explicit tar option when creating the archive using `--tar-extra`; there are options on both GNU and BSD tar to override the user name or ID. For example you could try `--owner=name` with GNU tar.

**Comment by bojanbt6** [comment]
The installer is used on 300+ machines with different users (user IDs) so setting owner for the files might only cause problems.

Even so, if I use those flags (--owner=NAME, --numeric-owner, --no-acls, --no-same-owner) it still does not work which tells me the problem is in the format that tar uses and the operations that are connected to that handling.

I still think it could be useful to have a way to control the tar format via an option in Makeself when creating the archive (if a format flag is not present Makeself will use a default tar format) as it is almost impossible to predict all of the problems that could arise on different Linux distributions and environments with the format (example, right now 2.4.4. cannot be used in our environment without explicit modification in makeself.sh).

**Comment by megastep** [comment]
Mmh I would think giving it a owner name (something like `nobody`) that doesn't resolve on the machine extracting might work around the problem. That said I think it would be a good idea to have a way to override the format of archives with tar on the command line.

**Comment by megastep** [comment]
I'm adding a `--tar-format` option in 8e93fb3092d2fa49360aa2a39952804730b2db70 if you want to check it out

**Comment by bojanbt6** [comment]
Works like a charm. Thanks!!!

**Comment by megastep** [comment]
Cool! I'll release 2.4.5 with this change later today.
