### ISSUE TITLE
$GPG_EXTRA is not passed with --sign, hence signing key can't be specified

### ISSUE THREAD

**Issue by Ost3rbaer** [megastep/makeself#257]
I am referring to makeself 2.4.5. To sign archives with GPG there are two options provided

- --sign "passphrase"
- --gpg-extra "extra options to GPG"

however, the latter is not passed to GPG when creating signatures. The current code in line 768 reads (double back quotes due to markdown garbles ticket, actual code uses single ones):

`        SIGNATURE=``$GPG_PATH --pinentry-mode=loopback --batch --yes --passphrase "$GPG_PASSPHRASE" --output - --detach-sig $tmpfile | base64 | tr -d \\\\n``
`

after adding $GPG_EXTRA, i.e.

`        SIGNATURE=``$GPG_PATH --pinentry-mode=loopback --batch --yes $GPG_EXTRA --passphrase "$GPG_PASSPHRASE" --output - --detach-sig $tmpfile | base64 | tr -d \\\\n``
`

I can now specify the key to be used with `--gpg-extra '-u software@mycompany.com'` and

`./makeself --zstd --sign "" --gpg-extra "-u software@mycompany.com" --sha256 DIR archive.run title script-command`

works as intended and

`./archive.run --verify-sig software@mycompany.com`

succeeds.

**Comment by Ost3rbaer** [comment]
[makeself.patch.txt](https://github.com/megastep/makeself/files/7211077/makeself.patch.txt)

change as unified diff to avoid garbling caused by markdown

**Comment by megastep** [comment]
Thanks! I just merged your patch in 3114b013a974dcc75b0d21a9b51e351ef89d2f3d
