### ISSUE TITLE
doc: "archive prefix" should be "archive suffix" / "archive extension"

### ISSUE THREAD

**Issue by Artoria2e5** [megastep/makeself#259]
(Sorry for something this trivial -- I am having a hiatus from touching git.)

The current documentation states:
> It is recommended that the archive prefix be set to something like ‘.bz2.run’, so that potential users know that they’ll need bzip2 to extract it.

Since the '.run' stuff goes after the file name, it should be a "suffix" or "extension" instead.

**Comment by Artoria2e5** [comment]
Thanks! Here's another request (sorry for not opening an issue -- it's tiny): consider expanding the LSM acronym (Linux Software Map) in the first place it appears in the README. It's probably not that important.

**Comment by megastep** [comment]
Ok, I just expanded on the meaning of LSM in the README.
