### ISSUE TITLE
Makeself requires "script_args" despite being optional according to help text

### ISSUE THREAD

**Issue by AndersHogqvist** [megastep/makeself#261]
When executing makeself.sh without any arguments or with --help | -v the usage indicates that [script_args] is optional by being wrapped inside [ ] just as [args].

**How to replicate:**
Try to create an archive without script_args.
`makeself.sh . test.run "This is a test"`

**Expected result:**
Archive being created

**Actual result:**
Help text is printed with the following text at the bottom:
`Do not forget to give a fully qualified startup script name`

**Recommended solution**
Make [script_args] optional as it's apparently is supposed to be.

**Comment by megastep** [comment]
Thanks but I believe it is a little bit more complicated than that. Technically, the embedded script and its arguments are only required for archives extracting to a temporary directory (the default). 

If using `--notemp` when creating the archive then this requirement does not apply. However I agree that this documentation is misleading and should be clarified.
