### ISSUE TITLE
Too much memory consumption while archiving and self-extracting

### ISSUE THREAD

**Issue by sezerb** [megastep/makeself#267]
Scenario:
A folder having ~15 uncompressed container images (~5GB) and an install.sh script which loads these docker images and run containers. While archiving this folder with makeself, RAM consumption increases ~15GB and not freed. After I restart VM (WSL2), and try to self-extract the archive, during the extraction the RAM usage is also increases ~10GB and not freed after all. So one of the containers cannot run properly due to this resource limitation.

Do you have any idea about why consumed RAM is not freed after archiving completed or after extraction completed?

Any idea that I can give a try is welcome.

P.S. Please note that I'm working in WSL2

**Comment by megastep** [comment]
That is odd and I don't really use WSL myself, however Makeself just runs third-party archivers and compressors such as `tar` and `bzip2`. The lifetime of these processes should end once the script is done executing. It is up to your OS's memory management to clean that up so I'm inclined to think Windows is at fault here.

**Comment by megastep** [comment]
I would check if there's any leftover process hanging on your system that is somehow not terminated properly and still consuming large amounts of RAM. A good suspect would be one of these commands, `gzip` or `bzip2` or whichever compressor you picked for your archive.

**Comment by sezerb** [comment]
Hi megastep,

Thanks for your comments, after some investigation it is obvious that it's something related with WSL2 dynamics. When I check memory usage of gzip process, that is not too much. As far as I see, during the archiving and extracting processes memory is automatically increased and after let's say ~1h time, the memory consumption decreased.
