### ISSUE TITLE
Script doesn't detect terminal when run from pipe

### ISSUE THREAD

**Issue by lukas-w** [megastep/makeself#271]
The extraction script checks for a terminal using `tty -s` which tests whether standard input is connected to a terminal:

https://github.com/megastep/makeself/blob/e7eb0fda3c08fe113cf0de7bdc08cc6df1157bc0/makeself-header.sh#L568

However, when the script is run from a pipe via e.g. `cat installer.run | sh`, this test fails and a new terminal is opened even when already in one. A better way to test this may be `[ -t 1 ]` which tests standard output instead.

A possible use-case exposing this bug is running a downloaded script installer such as `curl -sS https://example.com/install.sh | sh`.

**Comment by megastep** [comment]
Thanks for this. As is often the case, I'm always trying to preserve backwards compatibility so I wonder if your `[ -t 1 ]` might be a bash-ism. `tty` is a standard Unix command that can be reasonably assumed to be available even on legacy systems.

**Comment by megastep** [comment]
However `test -t 1` might be a good enough alternative here.

**Comment by huangganggui** [comment]
Hi, @lukas-w ,
Did `cat installer.run | sh` or `curl -sS https://example.com/install.sh | sh`work for you?  I meet an error:   https://github.com/megastep/makeself/issues/320

**Comment by lukas-w** [comment]
It does, but our `https://example.com/install.sh` is a small wrapper script that downloads the actual `.run` installer and then runs it. Maybe this is the reason we're not seeing the error you're getting.
