### ISSUE TITLE
Initial creation temp archive

### ISSUE THREAD

**Issue by JGarcia1973** [megastep/makeself#275]
There should be an option to specify a path to create the initial mkself[0-9]*.tar archive. By default the makeself will create that temp archive in /tmp/mkself[0-9]*.tar. If the user has a separate /tmp partition with 10GB of space and their archive is 18GB, the compression will fail, causing makeself to crash.

**Comment by megastep** [comment]
There is no command-line option, however the script does look for the `$TMPDIR` environment variable (and defaults to `/tmp` if it is not set). So I would suggest you set that before creating your archive.
