### ISSUE TITLE
ESXi compatibility

### ISSUE THREAD

**Issue by rbcrwd** [megastep/makeself#282]
I recently had the pleasure of porting a tool to run on ESXi and ran into some incompatibilities with Makeself, some of which may be intractable. I'd like your input on this before submitting a PR.  The ESXi shell is a heavily stripped `busybox` implementation, lacking some typically available features.

* ESXi shell lacks `tr` ([example usage](https://github.com/megastep/makeself/blob/master/makeself-header.sh#L203)). I had to use `sed -e 's/ //g'` instead.
* The busybox `df` used in ESXi [lacks the -P flag](https://github.com/megastep/makeself/blob/master/makeself-header.sh#L95). I recognize this is used to ensure a consistent columnar structure, so struggle with the decision to patch it out permanently. Any thoughts?

**Comment by realtime-neil** [comment]
If this was my project, then I'd yell "POSIX compliance!", link to this...

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/df.html

...and summarily close this ticket.

@megastep , if I recall correctly, this might be the second time a busybox deficiency has resulted in an issue against Makeself.

**Comment by realtime-neil** [comment]
Replacing all instances of `tr` with the equivalent `sed` might be a good idea, though.

**Comment by rbcrwd** [comment]
Right, I'm not necessarily a fan of the second item, but Busybox is a reality that we all have to deal with at some point or another. I'm perfectly capable of maintaining my own internal fork, but would of course rather not. It would be trivial (however ugly) to add a logic branch to do one thing if it's Busybox (and the user gets to keep both broken pieces) and the normal thing if not.

I'm mainly testing the waters for what might be palatable; I'll submit a patch either way.

**Comment by realtime-neil** [comment]
@rbcrwd to add to the confusion, not every `busybox` is created equal:

```
$ command -v busybox
/bin/busybox

$ command -v busybox | xargs dpkg -S
busybox-static: /bin/busybox

$ command -v busybox | xargs dpkg -S | cut -d: -f1 | xargs apt-cache policy
busybox-static:
  Installed: 1:1.30.1-4ubuntu6.4
  Candidate: 1:1.30.1-4ubuntu6.4
  Version table:
 *** 1:1.30.1-4ubuntu6.4 500
        500 http://archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1:1.30.1-4ubuntu6 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal/main amd64 Packages

$ busybox df --help
BusyBox v1.30.1 (Ubuntu 1:1.30.1-4ubuntu6.4) multi-call binary.

Usage: df [-PkmhTai] [-B SIZE] [FILESYSTEM]...

Print filesystem usage statistics

	-P	POSIX output format
	-k	1024-byte blocks (default)
	-m	1M-byte blocks
	-h	Human readable (e.g. 1K 243M 2G)
	-T	Print filesystem type
	-a	Show all filesystems
	-i	Inodes
	-B SIZE	Blocksize
```

**Comment by realtime-neil** [comment]
@rbcrwd what kind of provenance can you supply regarding the `busybox` ESXi is using? What version is the code? What "extras" were added/dropped during its build?

**Comment by rbcrwd** [comment]
This is what I have from the v6.5 ESXi I've tested against, acknowledging that there are significantly more recent releases:

```
BusyBox v1.22.1 (2016-03-26 07:03:26 PDT) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2012.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list
   or: function [arguments]...

        BusyBox is a multi-call binary that combines many common Unix
        utilities into a single executable.  Most people will create a
        link to busybox for each function they wish to use and BusyBox
        will act like whatever it was invoked as.

Currently defined functions:
        [, [[, addgroup, adduser, ash, awk, basename, bunzip2, bzcat, bzip2, cat, chgrp, chmod, chown, chvt, cksum, clear, cp, crond, cut, date, dd, delgroup, deluser, diff, dirname, dnsdomainname, du, echo, egrep,
        eject, env, expr, false, fdisk, fgrep, find, fstrim, getty, grep, groups, gunzip, gzip, halt, head, hexdump, hostname, inetd, init, kill, ln, logger, login, ls, lzop, lzopcat, md5sum, mkdir, mkfifo, mknod,
        mktemp, more, mv, nohup, nslookup, od, passwd, poweroff, printf, readlink, reboot, reset, resize, rm, rmdir, sed, seq, setsid, sh, sha1sum, sha256sum, sha3sum, sha512sum, sleep, sort, stat, stty, sum, sync,
        tail, tar, taskset, tee, test, time, timeout, touch, true, uname, uniq, unlzop, unzip, usleep, vi, watch, wc, wget, which, who, xargs, zcat
```

**Comment by realtime-neil** [comment]
@rbcrwd and the `busybox df --help` ?

**Comment by realtime-neil** [comment]
@rbcrwd Wait, your initial comment was 

> The busybox df used in ESXi lacks the -P flag

But your last comment shows a busybox diagnostic message wherein `df` is conspicuously absent.

Does this `busybox` version `1.22.1` have `df` or not? If it does, then why doesn't it appear in the list of "defined commands"?

**Comment by rbcrwd** [comment]
I went looking because I noticed the same thing. I was laboring under the delusion that it would have been the BB included one, but that particular applet is indeed gone. Instead of being a symlink to busybox, it's a standalone 4kb Python script (which I suspect is beyond my purview to post). Indeed, it lacks `-P` support.

**Comment by realtime-neil** [comment]
That's... absolutely amazing. Nice job, VMWare.

Okay, what do we do with this python script? Find out which flags it supports and confine our `df` usage to that subset?

**Comment by rbcrwd** [comment]
We know what flags it supports because it at least supports `--help`:
```df --help
Usage: df [options]

Options:
  --version  show program's version number and exit
  -h         Human readable
  -m         Megabytes
  -k         Kilobytes
  -u         Show UUID instead of volume name
  --help
```

The lack of a Busybox version identifier is what initially suggested it was different, I just hadn't gotten back around to posting the details before you got excited :)

Fundamentally it's wrapping the command `esxcli storage filesystem list` and mangling that application's output. It is plausible that they've updated it since 6.5 and made it more compliant, but as with everything released, this shall live forever.

**Comment by realtime-neil** [comment]
Okay, understood. I guess I should find out how "POSIX output format" differs from the _de facto_ output format. Maybe there's a way to easily parse sloppy output from a non-compliant `df`.

**Comment by realtime-neil** [comment]
https://github.com/megastep/makeself/pull/283

**Comment by rbcrwd** [comment]
> Okay, understood. I guess I should find out how "POSIX output format" differs from the _de facto_ output format.

Historically I've had to leverage `-P` when the columnar organization matters. On my Mac, for example, `df -k` produces the following headers:
```
Filesystem     1024-blocks      Used Available Capacity iused     ifree %iused  Mounted on
/dev/disk1s5s1   488245288  15052212  80959088    16%  502080 809590880    0%   /
```
... whereas `df -kP` produces the following more-limited but standardized columns:
```
Filesystem     1024-blocks      Used Available Capacity  Mounted on
/dev/disk1s5s1   488245288  15052212  80959088    16%    /
```

On one randomly-selected Ubuntu server I checked, the distinction is spaces (`-k`) versus tabs (`-kP`).

For consuming applications in third-class languages (e.g., shell) that don't support nice things like negative array offsets, that's a crucial distinction. It appears that the `MS_diskspace` function is already accounting for some variability already anyway, the question really is whether other platforms overload that 3rd or 4th column rather than extend like MacOS does.

**Comment by realtime-neil** [comment]
@rbcrwd yep, my thoughts exactly. That `awk` is doing way more sanitizing than `df -P` is. I've opened a PR that simply drops the ESXi-unsupported option.

**Comment by megastep** [comment]
OK, merged your PR! Hope this fixes this without breaking anything else. :)

**Comment by rbcrwd** [comment]
We still have the `tr -> sed` transition incomplete, but I'll submit a PR for that.

**Comment by realtime-neil** [comment]
> We still have the `tr -> sed` transition incomplete, but I'll submit a PR for that.

@rbcrwd I got you, friend: https://github.com/megastep/makeself/pull/286

**Comment by rbcrwd** [comment]
@realtime-neil you live up to your handle, thanks for being more on the ball than I am!
