### ISSUE TITLE
Hide uncompression progress

### ISSUE THREAD

**Issue by Zabrane** [megastep/makeself#287]
Hi @megastep 

First of all, thanks for makeself. It really helps me almost everyday.
Just one little thing annoys me and would like to know if it's possible to hide it:
```
./myapp
Verifying archive integrity... 100% All good.
Uncompressing My awesome command line tool    100%

Usage: myapp [opts]
```

Is it possible to hide the first two lines from the output? These two:
```
Verifying archive integrity... 100% All good.
Uncompressing My awesome command line tool    100%
```

What i'd like to eventually see is just this:
```
./myapp
Usage: myapp [opts]
```

Help appreciated and thanks again

**Comment by megastep** [comment]
Hi, yes it is possible to hide the output by providing the `--quiet` argument on the command line. I realize this is not exactly what you are asking for, however Makeself is not really meant to be used to start normal commands, but rather extract and install them.

**Comment by megastep** [comment]
Feel free to make PR if you'd like as long as you keep that behavior opt-in.
