### ISSUE TITLE
Add bzip3 algorithm support

### ISSUE THREAD

**Issue by chloeeeS** [megastep/makeself#288]
I would like to see support for creating [bzip3](https://github.com/kspalaiologos/bzip3) archives with makeself as i've noticed it tends to offer better compression ratios than the currently supported algorithms. The readme included in the respository linked above shows a few benchmarks against other popular algorithms. It's already been packaged for and included in the repositories for many popular linux distributions, so it hopefully wouldn't suffer from a lack of availability.

**Comment by megastep** [comment]
Sure - this should be a trivial addition as we already support a bunch of other compression methods. I'm assuming this would be similar to the existing `bzip2` support with just a different command name? Feel free to submit a PR for this if you'd like.
