### ISSUE TITLE
Unable to run post extract script, getting "./scanner.run: 1:  eval: ./launcher.sh: not found" error and stop execution. 

### ISSUE THREAD

**Issue by happy-to-code-nm** [megastep/makeself#290]
Created a .run file using makeself and trying to install the same in linux machine facing the above error all the time.
Tried with many option extracting to current directory, using --keep option, extracting to usr/bin/test directory but no luck.
Looks like its unable to find the script file, when i tried  **ls** command the file is found.

Here is the details of the command run 
root@xxxxxxx:/home/ubuntu/test# sudo ./scanner.run
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Security Scanner installer  100%
**./scanner.run: 1: eval: ./launcher.sh: not found**

With debugging enabled

root@xxxxxxxxxx:/home/ubuntu/test# sh -x ./scanner.run
+ umask
+ ORIG_UMASK=0022
+ test n = n
+ umask 077
+ CRCsum=3875288075
+ MD5=3c35fe03a460be32ec86ad2fcfc973bb
+ SHA=0000000000000000000000000000000000000000000000000000000000000000
+ SIGNATURE=
+ TMPROOT=/tmp
+ USER_PWD=/home/ubuntu/test
+ export USER_PWD
+ dirname ./scanner.run
+ ARCHIVE_DIR=.
+ export ARCHIVE_DIR
+ label= Scanner installer
+ script=./exes/launcher.sh
+ scriptargs=--keep
+ cleanup_script=
+ licensetxt=
+ helpheader=
+ targetdir=exes
+ filesizes=59562408
+ totalsize=59562408
+ keep=y
+ nooverwrite=n
+ quiet=n
+ accept=n
+ nodiskspace=n
+ export_conf=n
+ decrypt_cmd=
+ skip=718
+ print_cmd_arg=
+ type printf
+ print_cmd=printf
+ test -d /usr/xpg4/bin
+ test -d /usr/sfw/bin
+ unset CDPATH
+ finish=true
+ xterm_loop=
+ noprogress=n
+ nox11=n
+ copy=none
+ ownership=n
+ verbose=n
+ cleanup=y
+ cleanupargs=
+ sig_key=
+ initargs=
+ true
+ break
+ test xn = xy -a xn = xy
+ id -u
+ test xn = xy -a 0 -ne 0
+ test xnone != xphase2
+ MS_PrintLicense
+ PAGER=more
+ test x != x
+ test xn = xn
+ tty -s
+ :
+ test xexes = x.
+ test xy = xy
+ test xn = xy
+ test xn = xn
+ echo Creating directory exes
Creating directory exes
+ tmpdir=exes
+ dashp=-p
+ mkdir -p exes
+ pwd
+ location=/home/ubuntu/test
+ test x != x1
+ MS_Check ./scanner.run
+ OLD_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/gam
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/nssl/bin
+ MD5_ARG=
+ exec
+ MD5_PATH=/usr/bin/md5sum
+ test -x /usr/bin/md5sum
+ test -x /usr/bin/md5sum
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/
+ exec
+ SHA_PATH=/usr/bin/shasum
+ test -x /usr/bin/shasum
+ test xn = xn
+ MS_Printf Verifying archive integrity...
+ printf Verifying archive integrity...
Verifying archive integrity...+ head -n+ tr -d
 718 ./scanner.run
+ wc -c
+ offset=18747
+ cat ./scanner.run+ wc -c

+ tr -d
+ fsize=59581155
+ expr 59581155 - 18747
+ test 59562408 -ne 59562408
+ verb=
+ i=1
+ echo+ cut -d  -f1
 3875288075
+ crc=3875288075
+ test -x /usr/bin/shasum
+ basename /usr/bin/shasum
+ test xshasum = xshasum
+ SHA_ARG=-a 256
+ echo+ cut -d  -f1
 0000000000000000000000000000000000000000000000000000000000000000
+ sha=0000000000000000000000000000000000000000000000000000000000000000
+ test x0000000000000000000000000000000000000000000000000000000000000000 = x0000
+ test x = xy
+ test -x /usr/bin/md5sum
+ basename /usr/bin/md5sum
+ test xmd5sum = xdigest
+ echo+ cut -d  -f1
 3c35fe03a460be32ec86ad2fcfc973bb
+ md5=3c35fe03a460be32ec86ad2fcfc973bb
+ test x3c35fe03a460be32ec86ad2fcfc973bb = x00000000000000000000000000000000
+ MS_dd_Progress ./scanner.run 18747 59562408
+ test xn = xy
+ file=./scanner.run
+ offset=18747
+ length=59562408
+ pos=0
+ bsize=4194304
+ test 4194304 -gt 59562408
+ expr 59562408 / 4194304
+ cut -b-32
+ eval /usr/bin/md5sum
+ /usr/bin/md5sum
+ blocks=14
+ expr 59562408 % 4194304
+ bytes=842152
+ dd ibs=18747 skip=1 count=0
+ expr 0 + 4194304
+ pos=4194304
+ MS_Printf      0%%
+ printf      0%%
     0% + test 14 -gt 0
+ test 4194304 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 4194304 / 595624
+ pcent=7
+ test 7 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         7 -lt 10
+ MS_Printf     7%%
+ printf     7%%
    7% + expr 4194304 + 4194304
+ pos=8388608
+ test 8388608 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 8388608 / 595624
+ pcent=14
+ test 14 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         14 -lt 10
+ MS_Printf    14%%
+ printf    14%%
   14% + expr 8388608 + 4194304
+ pos=12582912
+ test 12582912 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 12582912 / 595624
+ pcent=21
+ test 21 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         21 -lt 10
+ MS_Printf    21%%
+ printf    21%%
   21% + expr 12582912 + 4194304
+ pos=16777216
+ test 16777216 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 16777216 / 595624
+ pcent=28
+ test 28 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         28 -lt 10
+ MS_Printf    28%%
+ printf    28%%
   28% + expr 16777216 + 4194304
+ pos=20971520
+ test 20971520 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 20971520 / 595624
+ pcent=35
+ test 35 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         35 -lt 10
+ MS_Printf    35%%
+ printf    35%%
   35% + expr 20971520 + 4194304
+ pos=25165824
+ test 25165824 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 25165824 / 595624
+ pcent=42
+ test 42 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         42 -lt 10
+ MS_Printf    42%%
+ printf    42%%
   42% + expr 25165824 + 4194304
+ pos=29360128
+ test 29360128 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 29360128 / 595624
+ pcent=49
+ test 49 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         49 -lt 10
+ MS_Printf    49%%
+ printf    49%%
   49% + expr 29360128 + 4194304
+ pos=33554432
+ test 33554432 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 33554432 / 595624
+ pcent=56
+ test 56 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         56 -lt 10
+ MS_Printf    56%%
+ printf    56%%
   56% + expr 33554432 + 4194304
+ pos=37748736
+ test 37748736 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 37748736 / 595624
+ pcent=63
+ test 63 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         63 -lt 10
+ MS_Printf    63%%
+ printf    63%%
   63% + expr 37748736 + 4194304
+ pos=41943040
+ test 41943040 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 41943040 / 595624
+ pcent=70
+ test 70 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         70 -lt 10
+ MS_Printf    70%%
+ printf    70%%
   70% + expr 41943040 + 4194304
+ pos=46137344
+ test 46137344 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 46137344 / 595624
+ pcent=77
+ test 77 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         77 -lt 10
+ MS_Printf    77%%
+ printf    77%%
   77% + expr 46137344 + 4194304
+ pos=50331648
+ test 50331648 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 50331648 / 595624
+ pcent=84
+ test 84 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         84 -lt 10
+ MS_Printf    84%%
+ printf    84%%
   84% + expr 50331648 + 4194304
+ pos=54525952
+ test 54525952 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 54525952 / 595624
+ pcent=91
+ test 91 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         91 -lt 10
+ MS_Printf    91%%
+ printf    91%%
   91% + expr 54525952 + 4194304
+ pos=58720256
+ test 58720256 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 58720256 / 595624
+ pcent=98
+ test 98 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         98 -lt 10
+ MS_Printf    98%%
+ printf    98%%
   98% + expr 58720256 + 4194304
+ pos=62914560
+ test 62914560 -le 59562408
+ test 842152 -gt 0
+ dd bs=842152 count=1
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         intf  100%%
+ printf  100%%
 100%  + md5sum=3c35fe03a460be32ec86ad2fcfc973bb
+ test x3c35fe03a460be32ec86ad2fcfc973bb != x3c35fe03a460be32ec86ad2fcfc973bb
+ test xn = xn
+ MS_Printf  MD5 checksums are OK.
+ printf  MD5 checksums are OK.
 MD5 checksums are OK.+ crc=0000000000
+ verb=n
+ test x0000000000 = x0000000000
+ test xn = xy
+ expr 1 + 1
+ i=2
+ expr 18747 + 59562408
+ offset=59581155
+ test xn = xn
+ echo  All good.
 All good.
+ head -n 718 ./scanner.run
+ tr -d
+ wc -c
+ offset=18747
+ test xn = xy
+ test xn = xn
+ test xn = xopenssl
+ MS_Printf Uncompressing  Scanner installer
+ printf Uncompressing  Scanner installer
Uncompressing  Scanner installer+ res=3
+ test xy = xn
+ test xn = xn
+ MS_diskspace exes
+ df -kP+ awk { if ($4 ~ /%/) {print $3} else {print $4} }
 exes
+ tail -1
+ leftspace=47615508
+ test -n 47615508
+ test 47615508 -lt 201432
+ MS_dd_Progress+ cd exes
+ umask 0022
+ UnTAR xp
+ test xn = xn
+ tar xpvf -
+ MS_Decompress
+ test x != x
+ eval xz -d
+ xz -d
 ./scanner.run 18747 59562408
+ test xn = xy
+ file=./scanner.run
+ offset=18747
+ length=59562408
+ pos=0
+ bsize=4194304
+ test 4194304 -gt 59562408
+ expr 59562408 / 4194304
+ blocks=14
+ expr 59562408 % 4194304
+ bytes=842152
+ dd ibs=18747 skip=1 count=0
+ expr 0 + 4194304
+ pos=4194304
+ MS_Printf      0%%
+ printf      0%%
     0% + test 14 -gt 0
+ test 4194304 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 4194304 / 595624
+ pcent=7
+ test 7 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         7 -lt 10
+ MS_Printf     7%%
+ printf     7%%
    7% + expr 4194304 + 4194304
+ pos=8388608
+ test 8388608 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 8388608 / 595624
+ pcent=14
+ test 14 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         14 -lt 10
+ MS_Printf    14%%
+ printf    14%%
   14% + expr 8388608 + 4194304
+ pos=12582912
+ test 12582912 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 12582912 / 595624
+ pcent=21
+ test 21 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         21 -lt 10
+ MS_Printf    21%%
+ printf    21%%
   21% + expr 12582912 + 4194304
+ pos=16777216
+ test 16777216 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 16777216 / 595624
+ pcent=28
+ test 28 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         28 -lt 10
+ MS_Printf    28%%
+ printf    28%%
   28% + expr 16777216 + 4194304
+ pos=20971520
+ test 20971520 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 20971520 / 595624
+ pcent=35
+ test 35 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         35 -lt 10
+ MS_Printf    35%%
+ printf    35%%
   35% + expr 20971520 + 4194304
+ pos=25165824
+ test 25165824 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 25165824 / 595624
+ pcent=42
+ test 42 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         42 -lt 10
+ MS_Printf    42%%
+ printf    42%%
   42% + expr 25165824 + 4194304
+ pos=29360128
+ test 29360128 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 29360128 / 595624
+ pcent=49
+ test 49 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         49 -lt 10
+ MS_Printf    49%%
+ printf    49%%
   49% + expr 29360128 + 4194304
+ pos=33554432
+ test 33554432 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 33554432 / 595624
+ pcent=56
+ test 56 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         56 -lt 10
+ MS_Printf    56%%
+ printf    56%%
   56% + expr 33554432 + 4194304
+ pos=37748736
+ test 37748736 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 37748736 / 595624
+ pcent=63
+ test 63 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         63 -lt 10
+ MS_Printf    63%%
+ printf    63%%
   63% + expr 37748736 + 4194304
+ pos=41943040
+ test 41943040 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 41943040 / 595624
+ pcent=70
+ test 70 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                         70 -lt 10
+ MS_Printf    70%%
+ printf    70%%
   70% + expr 41943040 + 4194304
+ pos=46137344
+ test 46137344 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 46137344 / 595624
+ pcent=77
+ test 77 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                  + test 77 -lt 10
+ MS_Printf    77%%
+ printf    77%%
   77% + expr 46137344 + 4194304
+ pos=50331648
+ test 50331648 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 50331648 / 595624
+ pcent=84
+ test 84 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                  + test 84 -lt 10
+ MS_Printf    84%%
+ printf    84%%
   84% + expr 50331648 + 4194304
+ pos=54525952
+ test 54525952 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 54525952 / 595624
+ pcent=91
+ test 91 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                  + test 91 -lt 10
+ MS_Printf    91%%
+ printf    91%%
   91% + expr 54525952 + 4194304
+ pos=58720256
+ test 58720256 -le 59562408
+ dd bs=4194304 count=1
+ expr 59562408 / 100
+ pcent=595624
+ expr 58720256 / 595624
+ pcent=98
+ test 98 -lt 100
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                  + test 98 -lt 10
+ MS_Printf    98%%
+ printf    98%%
   98% + expr 58720256 + 4194304
+ pos=62914560
+ test 62914560 -le 59562408
+ test 842152 -gt 0
+ dd bs=842152 count=1
+ MS_Printf \b\b\b\b\b\b\b
+ printf \b\b\b\b\b\b\b                                                  + MS_Printf  100%%
+ printf  100%%
 100%  + test 0 -ne 0
+ test xn = xy
+ expr 18747 + 59562408
+ offset=59581155
+ test xn = xn
+ echo

+ cd exes
+ res=0
+ test x./exes/launcher.sh != x
+ test xn = xy
+ test xn = xy
+ eval "./exes/launcher.sh" "$@"
+ ./exes/launcher.sh
**./scanner.run: 1: eval: ./exes/launcher.sh: not found**
+ res=127
+ test 127 -ne 0
+ test xn = xy
+ MS_exec_cleanup
+ test xy = xy
+ test x != x
+ test xy = xn
+ eval true
+ true
+ exit 127

Please help to fix this issue ASAP.
Thanks

**Comment by narasimhamurthy2692** [comment]
I used from simple command to little complicated once, nothing worked.

Here are the commands that are tried.
1. makeself.sh --xz --complevel 5 ./exes endpoint.sh "Scanner installer" ./exes/post_exec.sh
2. makeself.sh ./exes ./scanner.run "sample installer" ./launcher.sh
3. makeself.sh --notemp --current --xz ./exes ./exes/scanner.run "Scanner installer" ./launcher.sh
am windows bash to create this and when I run on git bash command prompt seems like it is able to pick up the launcher.sh, and with the same file when I tried with an ssh it comes with errors in the post extraction.

**Comment by megastep** [comment]
If there is indeed a `launcher.sh` script at the root of your archive, I would advise to use `sh launcher.sh` or `bash launcher.sh` as your launch command instead of `./launcher.sh`

**Comment by narasimhamurthy2692** [comment]
I tried as suggested but no luck, Its coming back with 
**./sample.sh: 1: eval: sh post_exec.sh: not found**
**./sample.sh: 1: eval: bash post_exec.sh: not found**
We need to run some script after extraction, so we need a launch post extraction.

**Comment by megastep** [comment]
This actually sounds more like some issues with the scripts inside your archive...

**Comment by narasimhamurthy2692** [comment]
Not sure what actually the issue is:
here is the test file which I created to simulate this issue.
I have two files:

**launcher.sh with contents** 

#!/bin/sh
echo "Installed location" $USER_PWD
cp SecurityScanner.service /etc/systemd/system
#TODO Check if the file successfully copied or not 
# Refreshing the daemon process
sudo systemctl daemon-reload
#Start service
sudo systemctl start sample.service
#TODO Verify the service is started successfully or not

"sample.service" file with content

[Unit]
Description=Manage sample Scanner

[Service]
WorkingDirectory=/usr/bin/sample/Agent
# ExecStart=/jre/bin/java -Xms128m -Xmx256m -jar sample.jar
ExecStart=/jre/bin/java -jar /bin/sample.jar "/config"
#Type=forking use this for prod
Type=simple

User=root
Group=root
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target

Am trying to copy the sample.service file to system path and then start service from the launcher.sh file, we have something similar in our app to process. This is also coming the same issue.

Command that is run to generate archive is:
**makeself.sh ./test ./sample.sh "Sample Installer" "sh launcher.sh"**

Please give us some inputs what could be wrong here.
I really appreciate your response, 
Thank you so much.

**Comment by narasimhamurthy2692** [comment]
Here is the test folder that am trying to use on windows machine to generate archive.
https://drive.google.com/file/d/1a1mPcFfY1hfpwsgtgX9AAnAhjH2CmVol/view?usp=sharing

- Downloaded makeself files and added to environments
- Executed makeself.sh ./test ./sample.sh "Sample Installer" "sh launcher.sh" on the git bash command prompt which is installed in windows
- After generating archine, am copying the file to Linux instance that is created on AWS 
- For copying the files to using winscp 
- After that executing the copied file 

Please let us know if we need any other information.

**Comment by realtime-neil** [comment]
@narasimhamurthy2692 , that is helpful --- thank you for providing this information.

Assuming the "input directory" can be accessed as `./test`, then your invocation has the following problems:
* `test/launcher.sh` doesn't exist
* Assuming `launcher.sh` is an executable shell script (and not just a `source`-able shell fragment), then you might prefer to use `./launcher.sh` instead of `sh launcher.sh`.

**Comment by narasimhamurthy2692** [comment]
Oh, Its my bad, in the test file what we have **post_exec.sh** is actually the **launcher.sh**, tried with these changes as well but still facing the same problem.
Tried running fallowing command to generate archive file.
- makeself.sh ./test ./sample.sh "sample installer" ./test/launcher.sh
- makeself.sh ./test ./sample.sh "sample installer" ./launcher.sh
But still facing the same problem

output:
 sudo ./sample.sh
**Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing sample installer  100%
./sample.sh: 1: eval: ./test/launcher.sh: not found**

**Comment by realtime-neil** [comment]
@narasimhamurthy2692 Try starting with something like this:

```
# Create the directory called "test" within the current working directory.
mkdir -vp ./test

# Delete all existing contents within "test", just in case it already existed.
find ./test -mindepth 1 -delete

# Use a heredoc to create the shell script "launcher.sh" within the "test"
# directory.
cat >./test/launcher.sh <<'EOF'
#!/bin/sh

echo 'Hello, launcher.sh!'

exit 0
EOF

# Set the executable bits on the "launcher.sh" shell script.
chmod -v +x ./test/launcher.sh

# Create the self-extracting archive called "test.run".
makeself ./test ./test.run 'Hello, Test!' ./launcher.sh

# Verify that the self-extracting archive "test.run" is correct.
./test.run --help
./test.run --info
./test.run --lsm
./test.run --list
./test.run --check
./test.run
```

...and gradually increasing the complexity.

**Comment by narasimhamurthy2692** [comment]
Sure, will try and update on the same.
Thank you

**Comment by realtime-neil** [comment]
@megastep I think it's time to create Makeself LLC and start billing for support contracts. :D
