### ISSUE TITLE
Website: ZIP and TARBALL links only provide documentation

### ISSUE THREAD

**Issue by tresf** [megastep/makeself#312]
I'm not sure if this is intended, but the ZIP and TARBALL download links on the main website don't actually contain `makeself`, but rather, just the documentation (perhaps it's a copy of the github pages?)

<img width="400" alt="image" src="https://github.com/megastep/makeself/assets/6345473/9e46a8d0-b3a9-47d1-a9f0-0d26999e1f95">

Actual:
https://github.com/megastep/makeself/zipball/gh-pages

Expected:
https://github.com/megastep/makeself/archive/refs/heads/master.zip

If this is desired, please disregard. 🍻

**Comment by megastep** [comment]
Yeah, that's the template I've used for the website that by default comes with these auto-generated links. Surprised that they are broken though, I'll see what can be done.

**Comment by megastep** [comment]
Fixed the website.
