### ISSUE TITLE
Add option to skip validation of .run file?

### ISSUE THREAD

**Issue by randlega** [megastep/makeself#318]
Hello,

I'm wondering if there is any appetite for adding a feature which skips the extraction and validation of the embedded contents before trying the actual extraction and execution of file contents.

Based on my experience, it seems like there are at least two reads of the embedded contents:

1. read embedded contents, compute hashes, compare against expected values
2. if 1 is successful proceed with extracting the contents and executing the script

In our workflow, we have large installers (>10 GB) and re-reading the file every time a user wants to retry the install takes a fair bit of extra time if we have already ran through the process once with a known good file.

There may be a better workflow recommendation you can provide as well 😄

**Comment by the-real-neil** [comment]
@randlega can I assume you have already considered and rejected the `--nocrc` option?

That is, you _do_ want at least one checksum present and you _don't_ want its presence to force validation?

**Comment by randlega** [comment]
Correct. We would want the default behaviour to ensure integrity, but give a user the option to skip the integrity check.

Our primary case is an "expert" user who knows what they are doing. They will have run the installer at least once before hand on the same system.

Rather than tracking state of whether or not the installer has run, it _seems_ easiest to provide an override.

E.g.

`--nocheck`

Note: I'm willing to help make the change, I just wanted to see if there is any interest before submitting a PR.

**Comment by randlega** [comment]
Correct me if I'm wrong, but  I think using `--nocrc` would also prevent `--verify` from working on the other end of things. 

`--verify` is nice to have for our users.

I also acknowledge that using `sha256sum` or something similar outside of the installer achieves most of these same results, but I would appreciate the ability to skip the verification on-demand if it exists.

**Comment by the-real-neil** [comment]
@randlega you might be interested in the `SETUP_NOCHECK` functionality, apparently added in version 1.5.5.

https://github.com/megastep/makeself/commit/becadc34e0ceb521db50f5e23bd4ccba3cc7290d

For the record, this is the first time I'm seeing it. :smile:

**Comment by randlega** [comment]
Ahah. That does work. Nice that I don't have to rebuild my installers either. 

Should I make a PR to add it to the documentation? Or is it intentionally obscure 🤔

**Comment by megastep** [comment]
Ah! Well this has been in this code for over 20 years so it's probably overdue for some documentation. 😅

**Comment by randlega** [comment]
😄

Thanks for the quick responses!

**Comment by the-real-neil** [comment]
> Correct me if I'm wrong, but I think using --nocrc would also prevent --verify from working on the other end of things.

@randlega you're correct in that `--nocrc` exists as an option. The problem (for your use case) is that it is understood during archive _build_ time and not during archive _run_ time.
