### ISSUE TITLE
Script can not run when run from pipe

### ISSUE THREAD

**Issue by huangganggui** [megastep/makeself#320]
This is very nice tool and work very well for me. I create an installer for my app named xxx-installer.sh.
Everything is ok when I run `./xxx-installer.sh`.  and i got success 
```
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing xxx  100% 
```
But when I install it form url use `wget -O - http://localhost/8000/xxx-installer.sh | sh` I got error :
```
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21145615 (20M) [text/x-sh]
Saving to: ‘STDOUT’

-                              0%[                                              ]       0  --.-KB/s               Verifying archive integrity...head: cannot open 'sh' for reading: No such file or directory
cat: sh: No such file or directory
 Unexpected archive size.
-                              0%[                                              ]  80.00K  --.-KB/s    in 0.003s  


Cannot write to ‘-’ (Broken pipe).
```
and I try `cat xxx-installer.sh | sh` I got error: 
```
Verifying archive integrity...head: cannot open 'sh' for reading: No such file or directory
cat: sh: No such file or directory
 Unexpected archive size.
```

I just want to use `wget(or curl) | sh` download and run it at same time . 
Can anyone help me?

**Comment by megastep** [comment]
Yeah, unfortunately we already have a similar issue for this (#24) that has been open for over 10 years now.

The main problem is because of the way we implement the decompression, it requires access to a physical file, which does not work when piping it to another process (such as sh).

**Comment by huangganggui** [comment]
@megastep Thanks for your reply.
Do you have any suggestions(like other tools not using decompression) for me to use `wget(or curl) | sh`
Thanks again
