### ISSUE TITLE
Extract files from .run without executing it

### ISSUE THREAD

**Issue by darealshinji** [megastep/makeself#37]
Is there a way to simply extract the files distributed with a .run file without without executing it? Implementing such a function would be nice, something like `makeself --extract installer.run`

**Comment by champ0617** [comment]
why can not  I extract it??    It seems not to support noexec target  arguments
![image](https://user-images.githubusercontent.com/24335956/234752720-ec077560-414a-4371-82f9-7c4188568958.png)

**Comment by megastep** [comment]
There are two dashes for the arguments, i.e. `--noexec`
