### ISSUE TITLE
Add --nooutput or similar flag for binaries

### ISSUE THREAD

**Issue by thethomaseffect** [megastep/makeself#44]
I'm using makeself in a situation where I'd only like warnings and errors printed to console like -q when executing the outputted binary and not the

``` test
Verifying archive integrity... All good.
Uncompressing *
```

text currently present. This would allow piping the output of binaries to other commands/text files the same as if the `startup_script` has been run by itself. It would also imply the --noprogress flag. Is this something others would be interested in?

**Comment by thecodesmith** [comment]
I am also interested! This would help a workaround in my automated tests.

**Comment by megastep** [comment]
Sounds like a good idea.

**Comment by megastep** [comment]
Actually we already have a `--quiet` flag for archives. Is it not doing this?

**Comment by thecodesmith** [comment]
@megastep Thanks for the pointer! I have confirmed that it works for my scenarios.
