### ISSUE TITLE
append option breaks archive integrity

### ISSUE THREAD

**Issue by arkanovicz** [megastep/makeself#48]
Hi.

FYI, with master revision, the --append option seems to be breaking the archive integrity. When trying to open the resulting file, we get an MD5 checksum error.

It's ok with the 2.2.0.

**Comment by Marte2007** [comment]
Ran a few tests, the faulty commit is 3cac577c74517bd7d646abe1e8d3c3899882cc8b (Added progress indication for integrity check).

**Comment by aflat** [comment]
2.4 has the same issue. If I change the `md5sum=\'MS_dd_Progress` to `md5sum=\'MS_dd` in the makeself-header.sh the append option works.

**Comment by megastep** [comment]
I am not so sure that is the case in the current branch - if I switch to `MS_dd` in the current code it still breaks.

**Comment by aflat** [comment]
True, master fails still, but release-2.4.0 tag succeeds with that change.

**Comment by megastep** [comment]
Actually I am seeing the same behavior with the 2.4.0 release, using the new `appendtest`. So this might have been broken even earlier. I am testing this on macOS at the moment.

**Comment by megastep** [comment]
The last release for which this test passes seems to be 2.2.0 which is quite a long time ago.

**Comment by aflat** [comment]
It was broken in 2.4.0 as well, but in 2.4.0 changing from MS_dd_Progress
to just MS_dd still passes appendtest.

**Comment by aflat** [comment]
And now I'm seeing 2.4.0 with the change, still fail, on osx only. It works on centos 6 and 7, but still breaks on the mac. I guess I was always testing on a centos machine before.

2.4.0 without the change still fails on centos too.
