### ISSUE TITLE
Dependencies of makeself

### ISSUE THREAD

**Issue by ErikOlufson** [megastep/makeself#49]
Hello Stephane,

thanks for your great job done the last years. We would like to use makeself to install our software on embedded systems and while testing the setup natively on the boxes eval has been marked as missing.

I will asked the boxes distributor to add all missing dependencies. Do you have a list of them? Checking them on a debian derivate only shows bzip2 as a dependency. Eval as a part of bash which means bash is required at all?

Best regards,

Erik

**Comment by megastep** [comment]
Hi Erik,

Actually, Makeself is supposed to have as few dependencies as possible as I use it to install software on bare Unix boxes, some of those don't have bash. It should work with a bare Bourne shell (sh).

So while it does have external dependencies, they should all mostly be optional. You should be able to use it as is with simple compressed files (.Z) or even gzip if you have that on your embedded system. it is able to decompress bz2 if that's what you want to use to compress, in which case you would need the bzip2 command on the system. The Debian maintainers probably specified that dependency in their package but it is not strictly required.

**Comment by ErikOlufson** [comment]
Hi Stephane,

unfortunately we are using busybox. Any idea to handle it?

**Comment by ErikOlufson** [comment]
It has been an omission of mine. In one hand in /tmp wasn't enough free disc space and the interpreter line was pointing to /bin/bash though bash isn't available.

Anyway thanks for your reply! Go on with your great project!
