### ISSUE TITLE
Failing on non-ext filesystems

### ISSUE THREAD

**Issue by ikozic** [megastep/makeself#54]
Hi,

I've noticed that extraction is intermittently failing on VFAT (FAT32) and NTFS file systems when started from Linux. I've tried on both ARM and x86 architectures - sometimes it deadloops and sometimes it does extract the files (not sure if their integrity is good), but fails with the following message:

```
Verifying archive integrity... All good.
Uncompressing FW v1.0........Extraction failed.
Terminated 
```

Are NTFS and/or FAT going to be supported in the future?

**Comment by megastep** [comment]
Makeself doesn't deal with the specifics of filesystems directly, so this is more an artifact of the other commands it relies on (like `tar`).
