### ISSUE TITLE
makeself sets restrictive umask

### ISSUE THREAD

**Issue by zachad** [megastep/makeself#6]
Since commit 842dedfe1a1477237c5132dc3615fcf50dddcc65, makeself sets a very restrictive umask 077 on the files that it unpacks. This is especially bothersome when building archives with --notemp and --target to specify the location of the extracted archive, with the expected permissions.

Is it possible to override the umask through some additional option set at packaging-time?

**Comment by ymattw** [comment]
I see this is fixed in commit e75285d.
