### ISSUE TITLE
Finding MD5 binary fails if `which` is not available

### ISSUE THREAD

**Issue by wandernauta** [megastep/makeself#65]
It seems that the method makeself.sh uses to find md5sum, md5 or digest is not working correctly if `which` is not present. It falls back to `type`, which can output a human-readable message ("md5sum is /some/path/to/md5sum") rather than a path, which then gets passed to `test -x`. This means makeself prints "none, MD5 command not found" even though md5sum is available.

Replacing this snippet...

	MD5_PATH=`exec <&- 2>&-; which md5sum || type md5sum`
	test -x "$MD5_PATH" || MD5_PATH=`exec <&- 2>&-; which md5 || type md5`
	test -x "$MD5_PATH" || MD5_PATH=`exec <&- 2>&-; which digest || type digest`

...by this snippet...

	MD5_PATH=`command -v md5sum 2>/dev/null`
	test -x "$MD5_PATH" || MD5_PATH=`command -v md5 2>/dev/null`
	test -x "$MD5_PATH" || MD5_PATH=`command -v digest 2>/dev/null`

...seems to fix the issue on my machine ([ref](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html)).

**Comment by megastep** [comment]
This is mostly here for historical reasons. I'm not sure if that `command` syntax is widely available among all platforms we support (including a lot of old Unix ones).

That being said, we could potential use it as a fallback, probably right after we try `which`.

**Comment by wandernauta** [comment]
Works like a charm, thanks!

**Comment by ymattw** [comment]
Fall back to `type -p md5sum`?  This would print the path instead of a human readable message.

**Comment by megastep** [comment]
Yeah, however as I recall there was at least one Unix system that didn't support that option (and instead simply put out the path), so that's why it was this way.

**Comment by ymattw** [comment]
Understood.  Keep it then, current solution works fine.  By the way `which` is not installed by default in many base docker images, this fix benefits a lot. Thanks.
