### ISSUE TITLE
Add a test for root before copying/extracting files

### ISSUE THREAD

**Issue by tasso85** [megastep/makeself#73]
I would like to suggest adding an option to allow to check that the user is "root", either because using "sudo" or actually root, before performing any kind of copying/extracting.

In fact, if the installer requires root privileges, but those are not available, this could save quite some time if the installer is big.

**Comment by philrykoff** [comment]
I'll second that :-)

**Comment by philrykoff** [comment]
Here is a piece of code i graciously stole from SO for that use case ;-)

```
if [ ! $EUID = 0 ]; then
    printf "This script must be run with sudo or as root user.\n\n"
    exit 1
fi
```

**Comment by megastep** [comment]
This is a good idea and I actually have a use case for this myself. My main worry with the piece of code that @philrykoff  posted here is I am not sure that `$EUID` is a very portable variable we can depend on. Might have to use output from `id -u` instead.

**Comment by megastep** [comment]
Just implemented this, let me know how it works for you. I guess I should release a new version soon.

**Comment by philrykoff** [comment]
Works great - thanks for the extremely short + kind turnaround!

**Comment by tasso85** [comment]
I've noticed only today that this got implemented, I'll try right away.

I'm happy my advice helped :)
