### ISSUE TITLE
Extract files from installer without running it?

### ISSUE THREAD

**Issue by Higgs1** [megastep/makeself#75]
Hello! I think Makeself has been really great, but I really think there should be some way to extract the files without executing the installer.

I did some Googling and I couldn't find anything, except for this: https://github.com/megastep/makeself/issues/37 but they apparently had a different issue since —noexec helped them. I agree however that there should be something like `makeself --extract installer.run`

Is there some simple-ish script I can use to extract the contents of the installer without having to execute it? I'll be working on a script in the meanwhile and I'll post it here if I get there first, but help would be nice! I also think implementing a `makeself --extract` option would be great.

Thanks :)

**Comment by megastep** [comment]
Well in this case the script is the archive itself (that's pretty much the whole point). I suppose you could look at the header of the file and extract what you want from there. Mostly it counts the number of lines to skip before the start of the compressed tar file so it's simple easy enough to do by hand if you're so inclined.

**Comment by Higgs1** [comment]
I actually just did and found out it was actually a MojoSetup installer... So the Makeself ends after 520 lines, followed by the archive which just contains MojoSetup. The actual data is located after that so now I'm just trying to figure that part out.
