### ISSUE TITLE
checking minimum libc version while bootstrapping to run elf  ?

### ISSUE THREAD

**Issue by kangjoni76** [megastep/makeself#76]
Thanks for useful project, is there any ideas to check minimum requried libc version via custom command ? Im not good at bash scripting or is this could be considered as feature request?

many thanks.

**Comment by megastep** [comment]
Hi,

Typically this is the kind of thing that is done within the script you provide to Makeself to be launched after extraction. I've used this exact kind of thing in scripts launching the loki_setup installer, for instance.

This tends to be a pretty unreliable test though, there are a number of ways to do it depending on the Linux version in use, from a simple grep of /lib/libc.so to using a package manager such as rpm or dpkg. It really depends on your target usage.
