### ISSUE TITLE
Feature Request: Expose original working directory to startup script

### ISSUE THREAD

**Issue by scottescue** [megastep/makeself#80]
I need a way to determine in my startup script from what directory the archive script was called. I need to know the original working directory, if you will.  As far as I can tell there's not a way to do this currently.
#### Scenario:

My archive script is located at `/home/scott/deploy.run`.  I need to passthrough a `--configFile` argument to my startup script.  My config file is located at `/home/scott/config.yml`.  

It's perfectly reasonable for the person executing my archive script to expect to pass a relative config file path, like so:

``` bash
./deploy.run -- --configFile config.yml
```

When that command is executed, my archive is extracted to `/var/folders/wm/_blahblah/T/selfgz1234`, which is what my startup script sees as the working directory.

The problem is that my startup script has a config file value of 'config.yml', but has no way to know the archive script was called from `/home/scott`.  I need to be able to determine that original working directory so I can resolve the fully qualified path of the config file.
#### One Possible Solution:

I've worked around this in my project by modifying makeself-header.sh to export a MAKESELF_PWD environment variable.  My startup script uses that variable to resolve file paths.  I suppose the original working directory could also be passed as an argument to the startup script, but that might not be backward compatible.

I'd be glad to put together a pull request if others agree this would be a useful addition, and there's consensus on the best solution.

**Comment by rbcrwd** [comment]
I think a76ca2d referenced this in error.

This is really needed; sometimes the tools makeself encapsulates need to use the randomly-named temporary directory to avoid conflicting with other invocations, but also need to interact with (store permanent data in) the directory the tool is running from.  This can't be achieved with $OLDPWD or pushd/popd, but instead is going to have to use some kind of environmental signal to convey this information.

My vote is for using an environment variable.  I'll fork a pull request shortly.

**Comment by rbcrwd** [comment]
Actually, no need for me to create a pull request - 10fa357b addressed this problem in December 2013, but @megastep hasn't cut a release since April 2013.

**Comment by megastep** [comment]
That's true, if you just check out the current code on Github you will get it but we are way overdue for a release. I'm gonna do one soon.

**Comment by rbcrwd** [comment]
FWIW, the v2.3.0 release addressed this issue for me; I'd consider it closed.
