### ISSUE TITLE
Invalid characters in EULA text prevents usafe of --license option

### ISSUE THREAD

**Issue by nmontmarquette** [megastep/makeself#82]
I got a few cases where the --license option won't work because of invalid or incompatible characters in the EULA document.

**Comment by megastep** [comment]
In the text itself or in the filename?

**Comment by nmontmarquette** [comment]
In the text itself including: odd quotes characters and some other I can't remember although I could find out if you want. All those were preventing as-is-assignation to the 'content' variable. I though a simple enough solution was just to encode/compress or just encode base. Any content could be used without modifications.

**Comment by davidyscott** [comment]
I ran into this as well --- with the COPYING license file included with makeself itself!

**Comment by vutny** [comment]
Seems to be already fixed in master, @megastep
