### ISSUE TITLE
makeself-2.3.0 incompatible with Solaris 10 (perhaps others)

### ISSUE THREAD

**Issue by rbcrwd** [megastep/makeself#92]
Change 436cf306fe05ab4d4805d3fda69660faac8eb4a5 added a call to "id -u", which is not supported in Solaris 10.  The /usr/xpg4/bin/id binary does support the "-u" option, but that's not called explicitly.

This may be bypassed, of course, by fiddling with $PATH order.  Unfortunately, pure-Bourne shell doesn't populate the $UID variable, so it seems the right answer will be slightly more complex than I'd wish.

**Comment by rbcrwd** [comment]
A [poor] resolution could be to just use 'id' naked and parse it:
`id | sed -e 's/.*uid=\([0-9]*\).*/\1/'`

**Comment by megastep** [comment]
Thanks for pointing this out as I really need Solaris 10 support for this. I'm pretty sure I've explicitly changed `$PATH` to add explicit paths in front for some platforms, so I wonder if it might be a better option.

**Comment by megastep** [comment]
Indeed this is what I was doing already in `makeself-header.sh`, it seems like it might need to be used for some of the newer code making these calls.

**Comment by rbcrwd** [comment]
The binaries in /usr/xpg4 are, in general, more friendly to modern usage.  If you already change `$PATH`, that may be the appropriate answer.

For example, /bin/tr on Solaris 10 doesn't support the same character-class syntax other versions of tr (including that in /usr/xpg4) do.

**Comment by megastep** [comment]
I'm thinking of changing that PATH earlier in the script to avoid problems on Solaris, instead of piece-meal when `id -u` was being called.

**Comment by rbcrwd** [comment]
Your call - I'd be happy with any solution that works seamlessly.

**Comment by megastep** [comment]
I just pushed a commit to try to fix that. Can you try it on your Solaris system?

**Comment by rbcrwd** [comment]
As noted in the code comment, the `export` will have to be mildly different, but otherwise it checks out.

**Comment by rbcrwd** [comment]
I created a pull request #93 to address that.

**Comment by megastep** [comment]
Thanks - guess that was an oversight.

**Comment by nohuhu** [comment]
I can confirm the PR above fixes the issue for Solaris 10. I bumped into it just yesterday and spent some time troubleshooting until I realized that it's already fixed in the master branch.

**Comment by megastep** [comment]
Yeah, I guess I should release 2.3.1 soon.

**Comment by rbcrwd** [comment]
Any update on a 2.3.1 release?

**Comment by megastep** [comment]
Thanks for reminding me, I'll try to push it out this week.

**Comment by megastep** [comment]
2.3.1 release was just pushed out.
