### ISSUE TITLE
Error in MD5 checksums when I use the --quiet argument

### ISSUE THREAD

**Issue by ardeidae** [megastep/makeself#97]
Hi!
Firstly, I want to thank you for your work :)
I'm making a makeself archive with this command line:
```
makeself.sh \
     --notemp \
     --bzip2 \
     "files/" \
     "my_archive.bz2.run" \
     "Hello" \
     ./setup.sh "some-arguments"
```

When I run my installer with the --check argument, no problem:
```
sh my_archive.bz2.run --check
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
```

When I run my installer without argument, the installation is done right:
```
sh my_archive.bz2.run
Creating directory files
Verifying archive integrity...  100%   All good.
Uncompressing Hello 100%
```

But when I run my installer with the --quiet argument, a problem occurs:
```
sh my_archive.bz2.run --quiet
Error in MD5 checksums: d41d8cd98f00b204e9800998ecf8427e is different from 09d483a36f78a640666b9e3ff19503af
```

**Comment by megastep** [comment]
Interesting, that sounds like a bug. Are you using the current version from git to exhibit this behavior?

**Comment by ardeidae** [comment]
Here is the version number:
```
./makeself.sh --version
Makeself version 2.3.0
```

**Comment by megastep** [comment]
I can not reproduce this with the current version (the soon to be 2.3.1, as in the repo right now). What OS are you running this on?

**Comment by ardeidae** [comment]
This is MacOS 10.11.6

**Comment by megastep** [comment]
Not happening with 10.12.4 here at least...

**Comment by ardeidae** [comment]
I've tried to build the same archive on Debian 7.3. The --quiet option works great.
I've tried to execute the archive build on MacOS 10.11.6 on Debian 7.3, no problem.
So it seems this is the extract process on MacOS 10.11.6 which is problematic.

I've removed from my PATH brew coreutils and gnu-tar, this doesn't help.

Do you need something to help you to find the problem?

**Comment by megastep** [comment]
I think a likely candidate for this might be your `bzip2` binary on the Mac. It doesn't ship standard with the OS so it's likely built from somewhere else. Maybe Homebrew too?

**Comment by ardeidae** [comment]
OK, I will try without bzip2. But why the --check option works?

Le 5 mai 2017 11:30 AM, "Stéphane Peter" <notifications@github.com> a
écrit :

**Comment by ardeidae** [comment]
Without the --bzip2, I get the same problem.

**Comment by megastep** [comment]
Another possible explanation would be weird versions of `md5` or `md5sum` on your system.

**Comment by ardeidae** [comment]
I will inspect this tuesday, but why does it work with --check option ?

**Comment by ardeidae** [comment]
How can I check this is due to a bad md5 version?

**Comment by megastep** [comment]
Run `which md5` and `which md5sum` and see if the location for any of these commands is a bit exotic (the regular `md5` command on Mac is in /sbin). Maybe you're picking up one from Homebrew or other.

**Comment by ardeidae** [comment]
Hi!
Originally, I had these locations.

```
which md5
/sbin/md5

which md5sum
/usr/local/opt/coreutils/libexec/gnubin/md5sum
```

But, I removed from my PATH brew coreutils and gnu-tar, this doesn't help.
Now, I have this result:

```
which md5
/sbin/md5

which md5sum
echo $?
1
```

The --quiet switch still doesn't work.
